// Wortliste: [Antwort, Hinweis, (weitere Hinweise …)]
// Umlaute/ß in Antworten sind erlaubt – sie werden zu AE/OE/UE/SS umgewandelt.
// Leerzeichen und Bindestriche werden entfernt.
const WORDS = [
  // ---------- Internet, Tech & Apps ----------
  ["YOUTUBE", "Videoplattform, die 2005 gegründet wurde", "Hier laufen Tutorials, Musikvideos und Katzenclips"],
  ["PYTHON", "Programmiersprache, benannt nach einer britischen Comedytruppe", "Programmiersprache mit Schlangen-Logo"],
  ["TESLA", "Elektroauto-Marke aus Elon Musks Konzern"],
  ["WHATSAPP", "Messenger, der seit 2014 zu Facebook bzw. Meta gehört", "App mit den zwei blauen Häkchen"],
  ["NETFLIX", "Streamingdienst mit vielen Eigenproduktionen", "Streamingdienst hinter „Stranger Things“"],
  ["LINUX", "Open-Source-Betriebssystem mit vielen Distributionen", "Betriebssystem mit Pinguin-Maskottchen"],
  ["PNG", "Dateiformat für transparente Bilder"],
  ["PDF", "Dateiformat, in dem man Rechnungen verschickt", "Dokumentformat, das überall gleich aussieht"],
  ["GIF", "Bildformat für kurze, lautlose Animationen"],
  ["JPEG", "Gängiges Dateiformat für Fotos"],
  ["SPOTIFY", "Musikstreamingdienst aus Schweden"],
  ["INSTAGRAM", "Fotoplattform mit Stories und Reels"],
  ["TIKTOK", "App für kurze Hochkant-Videos"],
  ["EMOJI", "Kleines Bildchen in Chatnachrichten", "Daumen hoch oder Tränen lachendes Gesicht, zum Beispiel"],
  ["SELFIE", "Foto, das man von sich selbst macht"],
  ["HASHTAG", "Schlagwort mit Raute davor"],
  ["PODCAST", "Audioformat, das man abonnieren kann", "Gesprächssendung für die Ohren, oft beim Pendeln gehört"],
  ["WLAN", "Funknetz, nach dessen Passwort Gäste als Erstes fragen"],
  ["ROUTER", "Gerät, das man aus- und wieder einsteckt, wenn das Internet spinnt"],
  ["AKKU", "Ist beim Handy immer dann leer, wenn man es braucht"],
  ["APP", "Programm auf dem Smartphone"],
  ["UPDATE", "Wird gern im ungünstigsten Moment installiert", "Software-Aktualisierung"],
  ["PASSWORT", "Sollte nicht „123456“ lauten"],
  ["BROWSER", "Programm zum Surfen im Netz"],
  ["GOOGLE", "Suchmaschine, die zum Verb wurde"],
  ["WIKIPEDIA", "Freie Online-Enzyklopädie"],
  ["AMAZON", "Onlinehändler, gegründet von Jeff Bezos"],
  ["EBAY", "Plattform für Auktionen und Kleinanzeigen"],
  ["PAYPAL", "Online-Bezahldienst, mit dem man Freunden Geld schickt"],
  ["IPHONE", "Smartphone von Apple"],
  ["ANDROID", "Smartphone-Betriebssystem von Google"],
  ["WINDOWS", "Betriebssystem von Microsoft"],
  ["CLOUD", "Online-Speicher für Fotos und Dateien"],
  ["BLOG", "Online-Tagebuch oder Webseite mit Artikeln"],
  ["INFLUENCER", "Macht auf Instagram Werbung für Produkte"],
  ["FOLLOWER", "Abonnent auf Social Media"],
  ["MEME", "Witziges Bild, das sich im Netz rasend verbreitet"],
  ["SPAM", "Unerwünschte Werbe-E-Mails"],
  ["TROLL", "Provoziert absichtlich in Kommentarspalten"],
  ["BUG", "Programmfehler"],
  ["CHATBOT", "Programm, mit dem man per Text plaudern kann"],
  ["ALGORITHMUS", "Entscheidet, was man in seinem Feed zu sehen bekommt"],
  ["ZOOM", "Videokonferenz-Software, die in der Pandemie berühmt wurde"],
  ["HOMEOFFICE", "Arbeiten vom Küchentisch aus"],
  ["LOCKDOWN", "Englisches Wort für die Corona-Ausgangsbeschränkungen"],
  ["DROHNE", "Ferngesteuertes Fluggerät mit Kamera"],
  ["EBIKE", "Fahrrad mit Rückenwind aus der Steckdose"],
  ["PLAYSTATION", "Spielkonsole von Sony"],
  ["NINTENDO", "Japanischer Hersteller der Switch"],
  ["MINECRAFT", "Videospiel, in dem alles aus Klötzchen besteht"],
  ["FORTNITE", "Battle-Royale-Spiel mit Tanz-Emotes"],
  ["TETRIS", "Spieleklassiker mit fallenden Blöcken"],
  ["POKEMON", "Taschenmonster, die man fangen muss"],
  ["MARIO", "Klempner mit roter Mütze aus Videospielen"],
  ["TWITCH", "Streamingplattform, auf der Leuten beim Zocken zugeschaut wird"],
  ["DISCORD", "Chat-Plattform, beliebt bei Gamern"],
  ["BITCOIN", "Bekannteste Kryptowährung"],
  ["QRCODE", "Schwarz-weißes Quadrat zum Scannen mit dem Handy"],
  ["DOWNLOAD", "Herunterladen einer Datei"],
  ["TASTATUR", "Darauf tippt man am Computer"],
  ["LAPTOP", "Klappbarer Computer für unterwegs"],
  ["TABLET", "Flacher Computer mit Touchscreen, größer als ein Handy"],
  ["SMARTWATCH", "Uhr, die Schritte zählt und Nachrichten anzeigt"],
  ["DRUCKER", "Gerät, das genau dann streikt, wenn man es braucht"],
  ["POWERBANK", "Mobiler Akku zum Nachladen des Handys"],
  ["USB", "Gängiger Anschluss für Sticks und Ladekabel"],
  ["HDMI", "Kabelanschluss zwischen Laptop und Fernseher"],
  ["EXCEL", "Tabellenkalkulation von Microsoft"],
  ["EMAIL", "Elektronischer Brief"],
  ["ANHANG", "Wird an E-Mails gern vergessen"],
  ["SCREENSHOT", "Bildschirmfoto"],
  ["AUTOKORREKTUR", "Ändert beim Tippen gern Wörter, die richtig waren"],
  ["SPRACHNACHRICHT", "Fünfminütiger Monolog statt einer kurzen Textnachricht"],
  ["FLUGMODUS", "Handy-Einstellung für Start und Landung"],
  ["NAVI", "Zeigt im Auto den Weg"],
  ["JAVASCRIPT", "Programmiersprache, die in jedem Webbrowser läuft"],
  ["HTML", "Auszeichnungssprache für Webseiten"],
  ["GITHUB", "Plattform, auf der Entwickler ihren Code teilen"],
  ["LIVESTREAM", "Übertragung in Echtzeit im Internet"],
  ["ONLINESHOP", "Geschäft im Internet"],
  ["AVATAR", "Profilbild oder Spielfigur im Netz"],
  ["LADEKABEL", "Hat man nie dabei, wenn der Akku leer ist"],
  ["STREAMEN", "Filme online schauen, ohne sie herunterzuladen"],
  ["LIKE", "Herzchen oder Daumen unter einem Post"],
  ["PIXEL", "Kleinster Bildpunkt auf einem Display"],
  ["CAPTCHA", "Test, der beweisen soll, dass man kein Roboter ist"],
  ["COOKIE", "Wird auf jeder Webseite per Banner angekündigt"],

  // ---------- Serien, Filme, Musik, Popkultur ----------
  ["BREAKINGBAD", "Kultserie mit Walter White"],
  ["FRIENDS", "Sitcom mit Ross, Rachel und dem Café Central Perk"],
  ["SIMPSONS", "Gelbe Zeichentrickfamilie aus Springfield"],
  ["HOMER", "Donut-liebender Familienvater aus Springfield"],
  ["DARK", "Deutsche Netflix-Serie über Zeitreisen in Winden"],
  ["TATORT", "Sonntagskrimi im Ersten"],
  ["HOGWARTS", "Zauberschule von Harry Potter"],
  ["GANDALF", "Zauberer aus „Der Herr der Ringe“"],
  ["YODA", "Kleiner grüner Jedi-Meister"],
  ["STARWARS", "Weltraumsaga mit Lichtschwertern"],
  ["MARVEL", "Comicverlag hinter Iron Man und Spider-Man"],
  ["BATMAN", "Superheld aus Gotham City"],
  ["BARBIE", "Puppe, deren Film 2023 ein riesiger Kinohit war"],
  ["OSCAR", "Wichtigster Filmpreis Hollywoods"],
  ["ADELE", "Britische Sängerin von „Hello“ und „Rolling in the Deep“"],
  ["EMINEM", "US-Rapper, bekannt als „Slim Shady“"],
  ["KARAOKE", "Singen zu Musik ohne Gesang, oft mit schiefen Tönen"],
  ["FESTIVAL", "Mehrtägiges Musikevent mit Zelten und Matsch"],
  ["SQUIDGAME", "Koreanische Netflix-Serie mit tödlichen Kinderspielen"],
  ["SHREK", "Grüner Oger aus dem Animationsfilm"],
  ["NEMO", "Clownfisch, den man finden muss"],
  ["ELSA", "Eiskönigin aus „Die Eiskönigin“"],
  ["MINIONS", "Gelbe Helfer mit Latzhose und Brille"],
  ["DISNEY", "Medienkonzern mit Micky Maus"],
  ["SPIDERMAN", "Superheld, der Netze schwingt"],
  ["JOKER", "Gegenspieler von Batman"],
  ["RAP", "Sprechgesang"],
  ["PLAYLIST", "Zusammengestellte Liste von Lieblingssongs"],
  ["ALBUM", "Sammlung von Songs eines Künstlers"],
  ["CHARTS", "Hitliste der meistgehörten Songs"],
  ["SITCOM", "Comedy-Serie mit eingespieltem Lachen"],
  ["STAFFEL", "Mehrere Folgen einer Serie zusammen"],
  ["SPOILER", "Verrät das Ende einer Serie, bevor man es gesehen hat"],
  ["BINGEWATCHING", "Eine ganze Staffel an einem Abend wegschauen"],
  ["TRAILER", "Kurze Vorschau auf einen Film"],
  ["POPCORN", "Kinosnack aus aufgeplatztem Mais"],
  ["ESC", "Gesangswettbewerb, bei dem Deutschland oft hinten landet (Abk.)"],

  // ---------- Marken & Alltag modern ----------
  ["IKEA", "Schwedisches Möbelhaus mit Köttbullar"],
  ["LEGO", "Bunte Klemmbausteine aus Dänemark"],
  ["PLAYMOBIL", "Spielfiguren aus Franken mit Dauerlächeln"],
  ["ADIDAS", "Sportmarke mit drei Streifen"],
  ["NIKE", "Sportmarke mit dem Swoosh"],
  ["SNEAKER", "Sportlicher Freizeitschuh"],
  ["HOODIE", "Pullover mit Kapuze"],
  ["JOGGINGHOSE", "Bequeme Hose, die man nicht nur zum Joggen trägt"],
  ["TATTOO", "Bild, das man unter der Haut trägt"],
  ["FLOHMARKT", "Markt für Gebrauchtes am Wochenende"],
  ["SECONDHAND", "Gebraucht gekauft, aus zweiter Hand"],
  ["LIEFERDIENST", "Bringt Essen bis an die Haustür"],
  ["UBER", "App für Fahrdienste"],
  ["AIRBNB", "Plattform für Ferienwohnungen von Privatleuten"],
  ["FLIXBUS", "Grüne Fernbusse"],
  ["VERSPÄTUNG", "Bei der Bahn eher die Regel als die Ausnahme"],
  ["ICE", "Schnellzug der Deutschen Bahn"],
  ["STAU", "Stillstand auf der Autobahn"],
  ["TEMPOLIMIT", "Auf deutschen Autobahnen ein Dauerstreitthema"],
  ["ELEKTROAUTO", "Fahrzeug, das an der Steckdose tankt"],
  ["LADESÄULE", "Tankstelle für E-Autos"],
  ["SOLARANLAGE", "Bringt Strom vom Dach"],
  ["KLIMAWANDEL", "Globale Erwärmung"],
  ["NACHHALTIG", "Umweltschonend und zukunftsfähig"],
  ["RECYCLING", "Wiederverwertung von Abfall"],
  ["PFAND", "Gibt's für leere Flaschen zurück"],
  ["TINDER", "Dating-App, bei der nach rechts gewischt wird"],
  ["WISCHEN", "Bewegung des Fingers über den Touchscreen"],
  ["GHOSTING", "Plötzlich ohne Erklärung den Kontakt abbrechen"],
  ["CRINGE", "Jugendwort für Fremdscham"],
  ["DIGGA", "Jugendsprachliche Anrede für den Kumpel"],
  ["CHILLEN", "Entspannen, abhängen"],
  ["NERD", "Technikbegeisterter Fachidiot"],
  ["GAMER", "Person, die viel Videospiele spielt"],
  ["ZOCKEN", "Umgangssprachlich: Videospiele spielen"],
  ["YOGA", "Entspannung mit Matte und herabschauendem Hund"],
  ["VEGAN", "Ganz ohne tierische Produkte"],
  ["VEGETARISCH", "Ohne Fleisch, aber mit Käse"],
  ["TOFU", "Sojaprodukt, beliebter Fleischersatz"],
  ["HAFERMILCH", "Pflanzlicher Milchersatz im Café"],
  ["AVOCADO", "Grüne Frucht auf dem Trendtoast"],
  ["SUSHI", "Japanisches Gericht mit Reis und rohem Fisch"],
  ["DÖNER", "Beliebtester Imbiss Deutschlands"],
  ["POMMES", "Frittierte Kartoffelstäbchen"],
  ["PIZZA", "Wird gern in einem flachen Karton geliefert"],
  ["CAPPUCCINO", "Kaffee mit Milchschaum"],
  ["ESPRESSO", "Kleiner, starker Kaffee"],
  ["BURGER", "Patty im Brötchen"],
  ["SMOOTHIE", "Püriertes Obst zum Trinken"],
  ["BUBBLETEA", "Getränk mit Tapiokaperlen"],
  ["CURRYWURST", "Berliner Imbissklassiker mit Soße"],
  ["FALAFEL", "Frittierte Kichererbsenbällchen"],
  ["NUTELLA", "Bekannte Nuss-Nougat-Creme"],
  ["BRUNCH", "Mischung aus Frühstück und Mittagessen"],
  ["FITNESSSTUDIO", "Ort für Hanteln und gute Neujahrsvorsätze"],
  ["MUSKELKATER", "Schmerz nach dem ersten Training seit Monaten"],
  ["JOGGEN", "Gemütliches Laufen"],
  ["KREDITKARTE", "Plastik zum Bezahlen, auch im Ausland"],
  ["KONTAKTLOS", "Bezahlen, indem man die Karte nur ans Gerät hält"],
  ["PAKET", "Wird gern beim Nachbarn abgegeben"],
  ["PAKETSTATION", "Gelber Kasten für Lieferungen"],
  ["MASKE", "Trug man in der Pandemie im Supermarkt"],
  ["IMPFUNG", "Pieks gegen Krankheiten"],
  ["SCHNELLTEST", "Corona-Test mit Ergebnis nach 15 Minuten"],
  ["HOMESCHOOLING", "Unterricht am Küchentisch"],

  // ---------- Fußball & Sport ----------
  ["BUNDESLIGA", "Höchste deutsche Fußball-Spielklasse"],
  ["ELFMETER", "Strafstoß im Fußball"],
  ["FUSSBALL", "Liebster Sport der Deutschen"],
  ["TOR", "Darauf hofft der Fan im Stadion"],
  ["STADION", "Arena für Fußballspiele"],
  ["ABSEITS", "Fußballregel, die keiner der Oma erklären kann"],
  ["SCHIRI", "Kurzform für den Mann oder die Frau mit der Pfeife"],
  ["TRIKOT", "Hemd der Fußballspieler"],
  ["OLYMPIA", "Sportevent mit fünf Ringen"],
  ["MARATHON", "Lauf über gut 42 Kilometer"],
  ["TENNIS", "Sport mit Schläger, Netz und gelbem Ball"],
  ["SCHWIMMEN", "Sport im Becken"],
  ["KLETTERN", "Sport an Wand oder Fels"],
  ["SKI", "Bretter für die Piste"],
  ["SURFEN", "Auf Wellen reiten – oder im Internet stöbern"],
  ["SKATEBOARD", "Brett mit vier Rollen"],

  // ---------- Normale Alltagswörter ----------
  ["KAFFEE", "Etwas, das man morgens dringend braucht"],
  ["EINFACH", "Nicht kompliziert"],
  ["WARTEZIMMER", "Hier wartet man beim Arzt"],
  ["TERMIN", "Ohne ihn wartet man beim Arzt noch länger"],
  ["WECKER", "Klingelt morgens viel zu früh"],
  ["SNOOZE", "Taste am Wecker für „noch fünf Minuten“"],
  ["FEIERABEND", "Ersehntes Ende des Arbeitstages"],
  ["WOCHENENDE", "Samstag und Sonntag zusammen"],
  ["URLAUB", "Freie Tage, die viel zu schnell vergehen"],
  ["MONTAG", "Unbeliebtester Wochentag"],
  ["FREITAG", "Letzter Arbeitstag der Woche für die meisten"],
  ["SONNTAG", "Ruhetag, an dem die Läden geschlossen haben"],
  ["BETT", "Darin verbringt man ein Drittel seines Lebens"],
  ["SOFA", "Gemütliches Möbel für Serienabende"],
  ["KISSEN", "Weiche Unterlage für den Kopf"],
  ["DECKE", "Wärmt auf dem Sofa – oder ist oben im Zimmer"],
  ["DUSCHE", "Ort für die besten Gesangsauftritte"],
  ["ZAHNBÜRSTE", "Sollte man alle drei Monate austauschen"],
  ["SCHLÜSSEL", "Sucht man ständig, kurz bevor man los muss"],
  ["BRILLE", "Sehhilfe auf der Nase"],
  ["REGENSCHIRM", "Bleibt zu Hause, wenn es dann doch regnet"],
  ["WETTER", "Beliebtes Smalltalk-Thema"],
  ["REGEN", "Nasses von oben"],
  ["SONNE", "Stern, um den die Erde kreist"],
  ["SOMMER", "Jahreszeit mit Eis und Freibad"],
  ["WINTER", "Kälteste Jahreszeit"],
  ["HERBST", "Jahreszeit, in der die Blätter fallen"],
  ["FRÜHLING", "Jahreszeit, in der alles zu blühen beginnt"],
  ["SCHNEE", "Weiße Flocken"],
  ["GEWITTER", "Unwetter mit Blitz und Donner"],
  ["NEBEL", "Dichte Wolke am Boden"],
  ["WIND", "Bewegte Luft"],
  ["REGENBOGEN", "Bunter Bogen am Himmel nach dem Schauer"],
  ["STRAND", "Sandiger Ort am Meer"],
  ["MEER", "Großes Salzwasser"],
  ["BERG", "Ziel jeder Wanderung"],
  ["WALD", "Viele Bäume auf einem Fleck"],
  ["INSEL", "Land, das ringsum von Wasser umgeben ist"],
  ["STADT", "Mehr als ein Dorf"],
  ["DORF", "Kleine Siedlung auf dem Land"],
  ["NACHBAR", "Nimmt die Pakete an"],
  ["FREUND", "Guter Bekannter, Kumpel"],
  ["FAMILIE", "Eltern, Kinder, Geschwister"],
  ["OMA", "Mutter der Mutter oder des Vaters"],
  ["OPA", "Vater der Mutter oder des Vaters"],
  ["BABY", "Neugeborenes"],
  ["HUND", "Bester Freund des Menschen"],
  ["KATZE", "Haustier, das das Internet regiert"],
  ["MAUS", "Klickt man am Computer – oder fängt die Katze"],
  ["VOGEL", "Tier mit Federn und Schnabel"],
  ["PFERD", "Reittier"],
  ["BIENE", "Insekt, das Honig macht"],
  ["SPINNE", "Achtbeiniges Tier in der Zimmerecke"],
  ["IGEL", "Stacheliges Tier"],
  ["FUCHS", "Schlaues Tier mit rotem Fell"],
  ["EULE", "Nachtaktiver Vogel"],
  ["ESEL", "Grautier mit langen Ohren"],
  ["KUH", "Liefert Milch"],
  ["PINGUIN", "Vogel im Frack, der nicht fliegen kann"],
  ["ELEFANT", "Größtes Landtier mit Rüssel"],
  ["GIRAFFE", "Tier mit dem längsten Hals"],
  ["GARTEN", "Grünfläche am Haus"],
  ["BALKON", "Kleiner Freisitz an der Wohnung"],
  ["KÜCHE", "Raum, in dem auf Partys alle stehen"],
  ["KÜHLSCHRANK", "Wird aus Langeweile mehrmals täglich geöffnet"],
  ["HERD", "Darauf wird gekocht"],
  ["OFEN", "Darin wird gebacken"],
  ["TOPF", "Kochgefäß mit Deckel"],
  ["PFANNE", "Darin brät man Spiegeleier"],
  ["GABEL", "Besteckteil mit Zinken"],
  ["LÖFFEL", "Besteckteil für die Suppe"],
  ["MESSER", "Besteckteil zum Schneiden"],
  ["TELLER", "Darauf liegt das Essen"],
  ["TASSE", "Gefäß für Kaffee oder Tee"],
  ["FLASCHE", "Gefäß mit Hals und Deckel"],
  ["BROT", "Grundnahrungsmittel vom Bäcker"],
  ["BUTTER", "Streichfett aus Milch"],
  ["KÄSE", "Wird aus Milch gemacht und hat manchmal Löcher"],
  ["APFEL", "Obst, das angeblich den Arzt fernhält"],
  ["BANANE", "Krumme gelbe Frucht"],
  ["ZITRONE", "Saure gelbe Frucht"],
  ["TOMATE", "Rotes Gemüse, das botanisch eine Frucht ist"],
  ["GURKE", "Grünes Gemüse im Salat"],
  ["NUDELN", "Beliebtestes Studentenessen"],
  ["REIS", "Körner, die zu Sushi und Curry gehören"],
  ["SUPPE", "Flüssiges Gericht aus dem Teller"],
  ["SALAT", "Grünes auf dem Teller"],
  ["KUCHEN", "Gebäck zum Nachmittagskaffee"],
  ["TORTE", "Mehrstöckiger Kuchen zum Geburtstag"],
  ["EIS", "Kalte Leckerei im Sommer"],
  ["SCHOKOLADE", "Süßigkeit aus Kakao"],
  ["HONIG", "Süßes von der Biene"],
  ["ZUCKER", "Macht süß"],
  ["SALZ", "Würzt, steht neben dem Pfeffer"],
  ["PFEFFER", "Scharfes Gewürz, steht neben dem Salz"],
  ["SENF", "Gehört zur Bratwurst"],
  ["KETCHUP", "Rote Soße für die Pommes"],
  ["WASSER", "Sollte man mehr davon trinken"],
  ["TEE", "Heißgetränk aus Blättern"],
  ["BIER", "Getränk aus Hopfen und Malz"],
  ["WEIN", "Getränk aus Trauben"],
  ["SAFT", "Gepresstes Obst zum Trinken"],
  ["FRÜHSTÜCK", "Erste Mahlzeit des Tages"],
  ["MITTAGSPAUSE", "Unterbrechung der Arbeit zum Essen"],
  ["ABEND", "Tageszeit nach Feierabend"],
  ["NACHT", "Dunkle Tageszeit"],
  ["MORGEN", "Beginn des Tages – oder der Tag nach heute"],
  ["GESTERN", "Der Tag vor heute"],
  ["UHR", "Zeigt die Zeit an"],
  ["KALENDER", "Hier stehen alle Termine drin"],
  ["GEBURTSTAG", "Jährliches Fest mit Torte und Kerzen"],
  ["GESCHENK", "Überraschung im bunten Papier"],
  ["PARTY", "Feier mit Musik und Getränken"],
  ["HOCHZEIT", "Feier, bei der man „Ja“ sagt"],
  ["WEIHNACHTEN", "Fest mit Baum und Geschenken"],
  ["OSTERN", "Fest mit bunten Eiern"],
  ["SILVESTER", "Letzter Tag des Jahres"],
  ["KOFFER", "Gepäckstück mit Rollen"],
  ["REISE", "Fahrt in die Ferne"],
  ["FLUGHAFEN", "Ort mit Gates und Sicherheitskontrollen"],
  ["HOTEL", "Unterkunft mit Rezeption"],
  ["ZELT", "Unterkunft beim Camping"],
  ["FAHRRAD", "Zweirad mit Pedalen"],
  ["AUTO", "Fahrzeug mit vier Rädern"],
  ["BUS", "Großes Fahrzeug im Nahverkehr"],
  ["ZUG", "Fährt auf Schienen"],
  ["TAXI", "Fahrzeug, das man sich heranwinkt"],
  ["AMPEL", "Zeigt Rot, Gelb und Grün"],
  ["PARKPLATZ", "In der Innenstadt schwer zu finden"],
  ["TANKSTELLE", "Ort für Sprit und späte Snacks"],
  ["BAUSTELLE", "Grund für die Umleitung"],
  ["SCHULE", "Ort, an dem man lernt"],
  ["HAUSAUFGABEN", "Lernstoff für zu Hause"],
  ["PRÜFUNG", "Test, für den man lernen sollte"],
  ["ZEUGNIS", "Gibt es am Ende des Schuljahres"],
  ["FERIEN", "Schulfreie Zeit"],
  ["STUDIUM", "Ausbildung an der Uni"],
  ["BÜRO", "Arbeitsplatz mit Schreibtisch"],
  ["CHEF", "Vorgesetzter"],
  ["KOLLEGE", "Mitarbeiter am Nachbartisch"],
  ["GEHALT", "Lohn, der am Monatsende kommt"],
  ["MIETE", "Monatliche Zahlung für die Wohnung"],
  ["STEUER", "Abgabe an den Staat"],
  ["RECHNUNG", "Liste mit dem zu zahlenden Betrag"],
  ["GELD", "Zahlungsmittel"],
  ["KONTO", "Darauf liegt das Geld bei der Bank"],
  ["EURO", "Währung in Deutschland"],
  ["MÜNZE", "Rundes Kleingeld"],
  ["EINKAUFEN", "Besorgungen im Laden machen"],
  ["SUPERMARKT", "Laden mit Lebensmitteln"],
  ["KASSE", "Hier bezahlt man im Laden"],
  ["ARZT", "Mediziner"],
  ["APOTHEKE", "Hier gibt es Medikamente"],
  ["KRANKENHAUS", "Klinik"],
  ["SCHNUPFEN", "Laufende Nase"],
  ["FIEBER", "Erhöhte Körpertemperatur"],
  ["PFLASTER", "Klebt auf kleinen Wunden"],
  ["MUSIK", "Klingt aus Kopfhörern und Lautsprechern"],
  ["GITARRE", "Saiteninstrument am Lagerfeuer"],
  ["KLAVIER", "Instrument mit schwarzen und weißen Tasten"],
  ["KONZERT", "Liveauftritt von Musikern"],
  ["KINO", "Großer Saal mit großer Leinwand"],
  ["FILM", "Geschichte in bewegten Bildern"],
  ["SERIE", "Geschichte in vielen Folgen"],
  ["BUCH", "Gebundene Seiten zum Lesen"],
  ["ROMAN", "Lange erzählte Geschichte"],
  ["ZEITUNG", "Täglich erscheinendes Nachrichtenblatt"],
  ["NACHRICHTEN", "Aktuelle Meldungen"],
  ["RADIO", "Läuft beim Autofahren"],
  ["FERNSEHER", "Großer Bildschirm im Wohnzimmer"],
  ["LANGEWEILE", "Gefühl, wenn nichts los ist"],
  ["STRESS", "Gefühl bei zu vielen Aufgaben"],
  ["GLÜCK", "Hat man beim Lotto"],
  ["LIEBE", "Starkes Gefühl der Zuneigung"],
  ["ANGST", "Gefühl bei Gefahr"],
  ["WUT", "Starker Ärger"],
  ["FREUDE", "Gefühl, wenn etwas Schönes passiert"],
  ["LACHEN", "Reaktion auf einen guten Witz"],
  ["SCHLAFEN", "Tut man nachts – oder sollte man zumindest"],
  ["TRAUM", "Kopfkino im Schlaf"],
  ["GÄHNEN", "Ansteckende Reaktion auf Müdigkeit"],
  ["HUNGER", "Gefühl eines leeren Magens"],
  ["DURST", "Gefühl, wenn man trinken muss"],
  ["MÜDE", "Zustand nach einer kurzen Nacht"],
  ["LAUT", "Nicht leise"],
  ["LEISE", "Nicht laut"],
  ["SCHNELL", "Nicht langsam"],
  ["LANGSAM", "Nicht schnell"],
  ["KLEIN", "Nicht groß"],
  ["ALT", "Nicht neu"],
  ["NEU", "Nicht alt"],
  ["WARM", "Nicht kalt"],
  ["KALT", "Nicht warm"],
  ["NASS", "Nicht trocken"],
  ["LEER", "Nicht voll"],
  ["VOLL", "Nicht leer"],
  ["TEUER", "Nicht billig"],
  ["LECKER", "Schmeckt gut"],
  ["SAUER", "Geschmack einer Zitrone – oder schlecht gelaunt"],
  ["SÜSS", "Geschmack von Zucker – oder niedlich"],
  ["SCHARF", "Geschmack von Chili"],
  ["BUNT", "Viele Farben auf einmal"],
  ["ROT", "Farbe der Liebe und der Ampel ganz oben"],
  ["BLAU", "Farbe des Himmels"],
  ["GRÜN", "Farbe von Gras"],
  ["GELB", "Farbe der Sonne und der Postautos"],
  ["LILA", "Farbe aus Rot und Blau"],
  ["LINKS", "Gegenteil von rechts"],
  ["RECHTS", "Gegenteil von links"],
  ["OBEN", "Gegenteil von unten"],
  ["UNTEN", "Gegenteil von oben"],
  ["FENSTER", "Glasöffnung in der Wand"],
  ["TÜR", "Öffnung zum Rein- und Rausgehen"],
  ["TREPPE", "Stufen zwischen den Stockwerken"],
  ["AUFZUG", "Fährt zwischen den Stockwerken"],
  ["WOHNUNG", "In der Großstadt schwer zu finden"],
  ["UMZUG", "Wechsel in eine neue Wohnung mit vielen Kisten"],
  ["KARTON", "Pappkiste"],
  ["SPÜLMASCHINE", "Gerät, über dessen Einräumen man streiten kann"],
  ["WASCHMASCHINE", "Darin verschwinden einzelne Socken"],
  ["SOCKE", "Verschwindet gern in der Waschmaschine"],
  ["STAUBSAUGER", "Gerät gegen Krümel und Staub"],
  ["MÜLL", "Kommt in die Tonne"],
  ["PUTZEN", "Sauber machen"],
  ["DUSCHGEL", "Seife aus der Flasche"],
  ["HANDTUCH", "Zum Abtrocknen nach dem Duschen"],
  ["JACKE", "Kleidungsstück gegen Kälte"],
  ["SCHAL", "Wärmt den Hals"],
  ["MÜTZE", "Wärmt den Kopf"],
  ["JEANS", "Hose aus blauem Denim"],
  ["SCHUH", "Gehört an den Fuß"],
  ["RUCKSACK", "Tasche für den Rücken"],
  ["HANDY", "Deutsches Wort für Smartphone"],
  ["FOTO", "Bild aus der Kamera"],
  ["KAMERA", "Gerät zum Fotografieren"],
  ["BRIEF", "Wird heute fast nur noch für Rechnungen verschickt"],
  ["BRIEFKASTEN", "Hier landet die Post"],
  ["POST", "Bringt Briefe und Pakete"],
  ["NAME", "Steht auf dem Klingelschild"],
  ["KLINGEL", "Knopf an der Haustür"],
  ["ADRESSE", "Straße, Hausnummer, Ort"],
  ["STRASSE", "Fahrbahn für Autos"],
  ["BRÜCKE", "Führt über den Fluss"],
  ["FLUSS", "Fließendes Gewässer"],
  ["SEE", "Stehendes Gewässer"],
  ["HIMMEL", "Blau bei gutem Wetter"],
  ["STERN", "Leuchtet nachts am Himmel"],
  ["MOND", "Nachts am Himmel, mal voll, mal halb"],
  ["ERDE", "Unser Planet"],
  ["BLUME", "Bringt man zum Muttertag mit"],
  ["BAUM", "Pflanze mit Stamm und Krone"],
  ["ROSE", "Blume mit Dornen"],
  ["GRAS", "Grüner Bodenbewuchs"],
  ["SPIEL", "Zeitvertreib mit Regeln"],
  ["WÜRFEL", "Hat sechs Seiten mit Punkten"],
  ["PUZZLE", "Legespiel mit vielen Teilen"],
  ["RÄTSEL", "Genau so etwas löst du gerade"],
  ["FRAGE", "Endet mit einem Fragezeichen"],
  ["ANTWORT", "Reaktion auf eine Frage"],
  ["IDEE", "Plötzlicher Einfall"],
  ["PLAN", "Vorhaben"],
  ["ZIEL", "Wo man ankommen will"],
  ["ANFANG", "Gegenteil von Ende"],
  ["ENDE", "Gegenteil von Anfang"],
  ["PAUSE", "Kurze Unterbrechung"],
  ["SPAZIERGANG", "Gemütliches Gehen an der frischen Luft"],
  ["PICKNICK", "Essen auf einer Decke im Park"],
  ["GRILLEN", "Sommerlicher Zeitvertreib mit Würstchen"],
  ["SCHWIMMBAD", "Ort mit Becken und Pommes"],
  ["SONNENBRAND", "Rote Haut nach zu viel Sonne"],
  ["SONNENCREME", "Schützt vor Sonnenbrand"],
  ["MÜCKE", "Summt nachts am Ohr"],
  ["ZWIEBEL", "Gemüse, das zum Weinen bringt"],
  ["KNOBLAUCH", "Würzknolle gegen Vampire"],
  ["KARTOFFEL", "Knolle für Pommes und Püree"],
  ["MÖHRE", "Orangefarbenes Gemüse"],
  ["ERDBEERE", "Rote Frucht des Frühsommers"],
  ["KIRSCHE", "Kleine rote Steinfrucht"],
  ["ORANGE", "Zitrusfrucht und Farbe zugleich"],
  ["MILCH", "Weißes Getränk von der Kuh"],
  ["JOGHURT", "Milchprodukt im Becher"],
  ["MÜSLI", "Frühstück aus Haferflocken und Nüssen"],
  ["BRÖTCHEN", "Kleines Gebäck vom Bäcker am Sonntagmorgen"],
  ["BÄCKER", "Verkauft Brot und Brötchen"],
  ["KELLNER", "Bringt im Restaurant das Essen"],
  ["TRINKGELD", "Extra für den Service"],
  ["RESTAURANT", "Ort, an dem man essen geht"],
  ["SPEISEKARTE", "Liste der Gerichte im Restaurant"],
  ["NACHTISCH", "Süßes nach dem Hauptgericht"],
  ["GEMÜTLICH", "Behaglich, kuschelig"],
  ["PÜNKTLICH", "Genau zur verabredeten Zeit"],
  ["SPONTAN", "Ohne lange Planung"],
  ["NEUGIERIG", "Will alles wissen"],
  ["FAUL", "Hat keine Lust, etwas zu tun"],
  ["LUSTIG", "Bringt zum Lachen"],
  ["EHRLICH", "Lügt nicht"],
  ["GEDULD", "Braucht man in der Warteschleife"],
  ["WARTESCHLEIFE", "Ort mit Dudelmusik am Telefon"],
  ["HOTLINE", "Telefonnummer für Kundenservice"],
  ["AUSREDE", "Vorwand, wenn man keine Lust hat"],
  ["VORSATZ", "Wird an Neujahr gefasst und im Februar vergessen"],
  ["DIÄT", "Wird oft am Montag begonnen"],
  ["SCHOKORIEGEL", "Snack für zwischendurch"],
  ["CHIPS", "Knuspriger Snack zum Fernsehabend"],
  ["GUMMIBÄRCHEN", "Bunte Fruchtgummis in Tierform"],
  ["SMALLTALK", "Gespräch übers Wetter"],
  ["GERÜCHT", "Unbestätigte Geschichte, die die Runde macht"],
  ["GEHEIMNIS", "Darf man nicht weitererzählen"],
  ["ÜBERRASCHUNG", "Unerwartetes Ereignis"],
  ["ABENTEUER", "Aufregendes Erlebnis"],
];
