// Stapel 1: kurze Alltagswörter (3–9 Buchstaben)
// Leitlinie: indirekt, mit Alltagsbezug oder Augenzwinkern. Keine reinen „Nicht X“-Hinweise.
WORDS.push(
  // ---------- 3 Buchstaben ----------
  ["AAL", "Fisch, der sich durch jede Lücke windet", "Wird in Hamburg gern geräuchert gegessen"],
  ["ABI", "Ihm geht eine Mottowoche voraus", "Reifeprüfung, kurz"],
  ["AHA", "Ausruf, wenn der Groschen fällt", "So klingt ein Erkenntnismoment"],
  ["ALM", "Sommerweide, auf der man Kuhglocken hört", "Hier gibt's nach der Wanderung Kaiserschmarrn"],
  ["AMT", "Dort zieht man eine Wartenummer", "Behörde – oder Posten, den jemand bekleidet"],
  ["ARM", "Hat einen Ellenbogen", "Mittellos"],
  ["ART", "Gattung im Zoo-Schild", "Auf diese ___ und Weise"],
  ["ASS", "Sticht beim Kartenspiel fast alles", "Wer darin glänzt, ist ein echtes …"],
  ["AST", "Sägt man besser nicht ab, wenn man darauf sitzt", "Ausleger am Baumstamm"],
  ["AXT", "Gehört zum Holzfäller-Look", "Im Escape Room meist aus Plastik"],
  ["BAD", "Hier stehen Zahnbürste und Föhn", "Kur-Präfix vieler Orte, z. B. vor Tölz"],
  ["BAR", "Ort für Cocktails mit Hocker", "Zahlungsart, die man im Café manchmal noch muss"],
  ["BAU", "Behausung von Fuchs und Dachs", "Hier tragen alle Helme"],
  ["BIO", "Siegel, das im Supermarkt einen Aufpreis bedeutet", "Schulfach mit Zellen und Fotosynthese (kurz)"],
  ["BOX", "Bluetooth-Lautsprecher, umgangssprachlich", "Kampfsport mit Handschuhen: …en"],
  ["DAX", "Börsenbarometer mit 40 Werten (Abk.)"],
  ["DNA", "Kommt in Krimis bei der Spurensicherung zur Sprache (engl. Abk.)"],
  ["DOM", "Der in Köln ist das Wahrzeichen der Stadt", "Hamburger Volksfest auf dem Heiligengeistfeld"],
  ["DUO", "Zwei auf einer Bühne", "Simon & Garfunkel waren eins"],
  ["EGO", "Wird bei Influencern gern gepflegt", "Das liebe Ich"],
  ["EHE", "Bund fürs Leben", "Wird am Standesamt geschlossen"],
  ["EID", "Wird mit erhobener Hand geleistet", "Hippokrates hat einen berühmten"],
  ["ELF", "Steht auf dem Platz, Ersatz auf der Bank", "Zahl, mit der im Rheinland der Karneval beginnt"],
  ["ENG", "Beschreibt die Jeans nach Weihnachten", "Schmal, mit wenig Platz"],
  ["ERZ", "Rohstoff aus dem Bergwerk", "Gestein, aus dem man Metall schmilzt"],
  ["FAN", "Trägt das Trikot im Stadion", "Hat ein Poster vom Star an der Wand"],
  ["FAX", "In deutschen Behörden ein zäher Überlebenskünstler", "Piepsendes Bürogerät aus den 90ern"],
  ["FEE", "Gibt im Märchen Wünsche frei", "Tinker Bell ist eine"],
  ["FIT", "Wird man im Studio – zumindest theoretisch", "In Form"],
  ["GAS", "Pedal rechts im Auto", "Brennt im Herd mit blauer Flamme"],
  ["GEL", "Sorgt für Igelfrisuren", "Darf im Handgepäck nur in kleinen Fläschchen mit"],
  ["GIN", "Spirituose, die mit Tonic einen Hype erlebte", "Wacholderschnaps"],
  ["GUT", "Note 2", "Ist manchmal der Feind von „besser“"],
  ["HAI", "Spielte die Hauptrolle in „Der weiße …“", "Flosse über Wasser, Panik am Strand"],
  ["HEU", "Trockenfutter für Pferd und Kaninchen", "Darin sucht man die Nadel"],
  ["HIT", "Ohrwurm in den Charts", "Erfolgsnummer"],
  ["HOF", "Bauernbetrieb – oder Platz hinterm Haus", "Hier residierten Kaiser und Könige"],
  ["HUT", "Kopfbedeckung mit Krempe", "Darunter bringt man etwas, wenn man sich einigt"],
  ["JET", "Kurz für Düsenflieger", "Privat… der Superreichen"],
  ["JOB", "Nebenher im Café oder hauptberuflich", "Arbeitsstelle, umgangssprachlich"],
  ["KAI", "Anlegestelle im Hafen", "Uferstraße für Schiffe"],
  ["KOI", "Edelkarpfen im Gartenteich", "Teurer japanischer Zierfisch"],
  ["KUR", "Aufenthalt zur Erholung, oft von der Kasse bezahlt", "Wird gern mit „Bad“ im Ortsnamen verbunden"],
  ["LKW", "Überholt sich auf der Autobahn gern minutenlang (Abk.)", "Laster, kurz"],
  ["LOB", "Lohnt sich mehr als Kritik", "Anerkennung vom Chef"],
  ["LOK", "Zieht die Waggons (kurz)", "Thomas ist eine kleine blaue"],
  ["LOS", "Bei der Tombola zieht man eins", "Startkommando"],
  ["MAI", "Monat der Maibäume und Tanz in den …", "Wonnemonat"],
  ["MIX", "Zusammenstellung, die der DJ macht", "Mischung"],
  ["MUS", "Wird aus gekochten Äpfeln gemacht", "Brei, z. B. zu Reibekuchen"],
  ["MUT", "Braucht man für den Sprung vom Zehner", "Gegenspieler der Angst"],
  ["NAH", "Um die Ecke", "Kurz davor"],
  ["NIL", "Fluss, an dem die Pyramiden stehen", "Afrikas Lebensader"],
  ["ODE", "Feierliches Gedicht, z. B. „An die Freude“"],
  ["OHM", "Einheit, die nach einem Physiker benannt ist (Widerstand)"],
  ["OHR", "Wird bei Ohrwürmern belagert", "Daran zieht man jemanden – oder hängt Ohrringe"],
  ["ORT", "Am Tatort zu finden", "Stelle, Platz"],
  ["OST", "Himmelsrichtung des Sonnenaufgangs", "Gegenteil von West"],
  ["PIN", "Wird am Kartenterminal abgefragt", "Vierstellige Geheimzahl"],
  ["PKW", "Personenkraftwagen (Abk.)"],
  ["POL", "Hier treffen sich alle Längengrade", "Nord oder Süd, beim Magneten auch Plus oder Minus"],
  ["POP", "Musikgenre von Taylor Swift", "Art, deren Ikone Andy Warhol war"],
  ["PUB", "Britische Kneipe", "Hier gibt's Fish & Chips zum Pint"],
  ["RAD", "Hat Speichen", "Schlägt der Pfau"],
  ["RAT", "Gibt man ungefragt am liebsten", "Hinweis, Empfehlung"],
  ["REH", "Bambi ist eins", "Scheues Waldtier"],
  ["ROH", "So isst man Sushi-Fisch", "Ungekocht"],
  ["RUF", "Eilt einem voraus", "Reputation"],
  ["RUM", "Piratengetränk", "Karibischer Zuckerrohrschnaps"],
  ["SAU", "Wird im Dorf rausgelassen, wenn man feiert", "Weibliches Schwein"],
  ["SET", "Satz beim Tennis", "Ort, an dem gedreht wird"],
  ["SMS", "Textnachricht aus der Zeit vor WhatsApp"],
  ["SOG", "Strömung, die zieht", "Gefährlich hinter Schiffen und Brandungen"],
  ["SPA", "Wellnessbereich im Hotel", "Belgischer Kurort und Formel-1-Strecke"],
  ["TAG", "Hat 24 Stunden", "Hashtag-Hälfte"],
  ["TAL", "Hier fließt meist ein Fluss", "Senke zwischen Bergen"],
  ["TAT", "Mehr wert als Worte", "Krimis suchen den Täter dazu"],
  ["TAU", "Glitzert morgens auf der Wiese", "Dickes Schiffsseil"],
  ["TOD", "Wird als Sensenmann dargestellt", "Ende vom Lied"],
  ["TON", "Material in der Töpferei", "Den gibt man an, wenn man bestimmt"],
  ["TOP", "Bauchfreies Oberteil", "Das Gegenteil von Flop"],
  ["TOT", "So ist ein Gerücht, das sich nicht mehr verbreitet", "Mausetot, nur kürzer"],
  ["TÜV", "Plakette alle zwei Jahre (Abk.)"],
  ["TYP", "Lockerer Ausdruck für einen Kerl", "Persönlichkeit: Er ist nicht mein …"],
  ["UFO", "Erscheint gern in Akte X", "Unbekanntes Flugobjekt"],
  ["UHU", "Große Eule – und Klebstoffmarke"],
  ["UNO", "Kartenspiel mit Plus-vier-Karte", "Hauptsitz in New York (Abk.)"],
  ["VAN", "Großraumauto für Familie oder Band", "Bulli, auf Neudeutsch"],
  ["VIP", "Hat das Bändchen für die Lounge", "Promi mit Sonderzugang"],
  ["WAL", "Größtes Tier der Erde", "Moby Dick ist einer"],
  ["WEB", "Englisch für das Netz", "World Wide …"],
  ["WEG", "Ist das Ziel, sagt ein Sprichwort", "Verschwunden"],
  ["WOK", "Pfanne für gebratene Nudeln", "Gewölbte asiatische Pfanne"],
  ["ZOO", "Tierpark mit Gehegen", "Hier gibt es Fütterungszeiten für Besucher"],

  // ---------- 4 Buchstaben ----------
  ["AFFE", "Primat, der sich gern laust", "Kletterkünstler im Urwald"],
  ["BALL", "Rund und muss ins Tor", "Tanzveranstaltung im Abendkleid"],
  ["BAND", "Spielt auf dem Festival", "Teil einer Buchreihe"],
  ["BANK", "Steht im Park – oder hat Filialen", "Hier verwaltet man sein Konto"],
  ["BART", "Wächst bei Hipstern gern lang", "Ist ab, wenn's vorbei ist"],
  ["BEIN", "Kann man sich ausreißen oder vertreten", "Hat ein Knie"],
  ["BILD", "Sagt mehr als tausend Worte", "Hängt im Rahmen"],
  ["BLEI", "Schweres Metall, früher im Benzin", "Gießt man an Silvester (früher)"],
  ["BOOT", "Sitzen alle im gleichen, wenn's ernst wird", "Ruder… oder Tret…"],
  ["BURG", "Ritterwohnsitz mit Zugbrücke", "Am Strand aus Sand gebaut"],
  ["CHOR", "Singt in der Kirche mehrstimmig", "Gruppe aus Sopran, Alt, Tenor und Bass"],
  ["DACH", "Hat das Haus über dem Kopf", "Darauf stehen Solarmodule"],
  ["DAME", "Steht beim Schach neben dem König", "Brettspiel, bei dem man springt und schlägt"],
  ["DEAL", "Abmachung, englisch", "Wird beim Pokern oder am Black Friday gemacht"],
  ["DIEB", "Ihn macht Gelegenheit", "Langfinger"],
  ["DING", "Sache, unbestimmt", "So nennt man Gegenstände, deren Namen man vergessen hat"],
  ["DOOF", "Umgangssprachlich: blöd", "Wie man etwas findet, das nervt"],
  ["DOSE", "Darin stecken Ravioli oder Energydrink", "Behälter aus Blech"],
  ["DUFT", "Weht aus der Bäckerei", "Angenehmer Geruch"],
  ["ECHO", "Antwortet einem in den Bergen", "Rückhall"],
  ["ECHT", "Kein Fake", "Jugendsprachlich: wirklich, im Ernst"],
  ["ECKE", "Hier steht man zur Strafe", "Freistoß von der Seitenlinie"],
  ["EDEL", "Wie ein Tropfen guten Weins", "Vornehm, hochwertig"],
  ["EHRE", "Wird man erwiesen", "Würde, Ansehen"],
  ["ELCH", "Ihm zu Ehren gibt es einen berühmten Ausweichtest für Autos", "Größter Hirsch Skandinaviens"],
  ["ENTE", "Falsche Zeitungsmeldung", "Quakt im Teich"],
  ["ERBE", "Bekommt man vom Testament", "Hinterlassenschaft"],
  ["FAIR", "So sollte Kaffee gehandelt werden", "Anständig, gerecht"],
  ["FASS", "Hat einen Boden, der manchmal ausgeschlagen wird", "Großer Holzbehälter für Wein"],
  ["FERN", "Sieht man mit dem Teleskop", "Weit weg"],
  ["FEST", "Weihnachten ist eins", "Wie ein Knoten, der hält"],
  ["FETT", "Jugendsprachlich: großartig", "Steckt reichlich in Chips"],
  ["FIES", "Gemein, hinterhältig", "So ist ein Cliffhanger am Staffelende"],
  ["FINK", "Darwins berühmter Vogel", "Kleiner Singvogel"],
  ["FLUG", "Man bucht ihn gern mit Handgepäck", "Kann Verspätung haben – wie die Bahn"],
  ["FORM", "Ist man in guter, wenn man fit ist", "Gestalt – oder Backbehälter"],
  ["FREI", "Steht auf dem Taxischild", "Gratis, ungebunden"],
  ["FROH", "Fröhlich, erleichtert", "___e Weihnachten!"],
  ["FUSS", "Hat fünf Zehen", "Längenmaß in der Luftfahrt"],
  ["GANS", "Landet zu Martini auf dem Teller", "Weißer Vogel, der Höfe bewacht"],
  ["GAST", "Ist nach drei Tagen wie Fisch, sagt man", "Besucher"],
  ["GOLD", "Gibt's für den ersten Platz", "Edelmetall in Barren"],
  ["GOLF", "Sport mit 18 Löchern", "VW-Bestseller"],
  ["GRAU", "Farbe des Novemberhimmels", "Farbe vieler Großstadtkatzen in der Nacht"],
  ["HAAR", "Wird beim Friseur geschnitten", "Findet man gern in der Suppe"],
  ["HAHN", "Kräht auf dem Mist", "Daraus kommt Wasser"],
  ["HALS", "Bekommt man nicht voll, wenn man gierig ist", "Kratzt bei Erkältung"],
  ["HAND", "Hat einen Daumen", "Wäscht die andere"],
  ["HART", "Wie ein Ei nach zehn Minuten", "Brett, das gebohrt werden will"],
  ["HASE", "Bringt zu Ostern die Eier", "Mümmelmann"],
  ["HAUS", "Tiny … – Trend für Minimalisten", "Gebäude zum Wohnen"],
  ["HAUT", "Größtes Organ des Menschen", "Bekommt Gänse…, wenn's spannend wird"],
  ["HEFT", "Hat Linien oder Kästchen", "Nimmt man in die Hand, wenn man die Führung übernimmt"],
  ["HELD", "Trägt im Film oft ein Cape", "Retter in der Not"],
  ["HELL", "Wie ein Zimmer mit großem Fenster", "Bayerische Biersorte"],
  ["HEMD", "Hat Kragen und Manschetten", "Näher als der Rock, sagt das Sprichwort"],
  ["HERZ", "Emoji in Rot, oft verschickt", "Pumpt rund um die Uhr"],
  ["HEXE", "Fliegt auf dem Besen", "Bibi Blocksberg ist eine"],
  ["HOCH", "Wetterlage mit Sonnenschein", "Wie ein Turm oder Berg"],
  ["HOSE", "Wenn's ernst wird, geht's um die …", "Jeans ist eine"],
  ["HUHN", "War es zuerst da oder das Ei?", "Legt Frühstückseier"],
  ["IGLU", "Kuppelbau aus Schneeblöcken", "Inuit-Behausung"],
  ["INFO", "Kurz für Auskunft", "Steht über dem Schalter am Bahnhof"],
  ["JAHR", "Läuft von Januar bis Dezember", "Wird mit Böllern verabschiedet"],
  ["JAZZ", "Musik mit Saxofon und Improvisation", "Louis Armstrongs Genre"],
  ["KAHL", "Wie Bäume im Winter", "Glatzköpfig"],
  ["KAMM", "Hat viele Zähne, beißt aber nicht", "Hat der Hahn auf dem Kopf"],
  ["KANU", "Paddelboot", "Damit fährt man auf dem Fluss durch die Wildnis"],
  ["KERN", "Steckt im Apfel", "Der harte …, der sich nicht unterkriegen lässt"],
  ["KIND", "Das ___ beim Namen nennen", "Hat Hausaufgaben und Ferien"],
  ["KINN", "Wird beim Nachdenken gestreichelt", "Unterster Teil des Gesichts"],
  ["KITA", "Hier werden Kleine morgens abgegeben (kurz)", "Krippe und Kindergarten zusammen, kurz"],
  ["KLAR", "Wie Wasser aus der Bergquelle", "Logisch, sowieso"],
  ["KLEE", "Vierblättrig bringt er Glück", "Futterpflanze auf der Weide"],
  ["KLUG", "Ist man hinterher immer", "Schlau"],
  ["KNIE", "Darauf geht man für einen Antrag", "Gelenk mit Scheibe"],
  ["KOCH", "Zu viele verderben den Brei", "Trägt eine weiße Mütze in der Küche"],
  ["KOPF", "Zerbricht man sich bei diesem Rätsel", "Gegenteil von Zahl beim Münzwurf"],
  ["KORB", "Bekommt man beim Flirten als Absage", "Darin landet der Basketball"],
  ["KRAN", "Dreht sich über der Baustelle", "Hebt Container im Hafen"],
  ["KRUG", "Geht so lange zum Brunnen, bis er bricht", "Bierglas mit Henkel"],
  ["KURZ", "Wie eine Hose im Sommer", "Fasst man sich, wenn man nicht abschweifen will"],
  ["KUSS", "Gibt's unter dem Mistelzweig", "Macht im Märchen aus dem Frosch einen Prinzen"],
  ["LAMM", "So geduldig ist jemand, der alles erträgt", "Junges Schaf"],
  ["LAND", "Hier gibt es mehr Kühe als Busse", "Staat"],
  ["LANG", "Wie eine Schlange vor dem Club", "Wie ein Gesicht bei Enttäuschung"],
  ["LAUB", "Wird im Herbst mit dem Bläser zusammengepustet", "Herbstblätter"],
  ["LIEB", "Nett, artig", "Wie ein Gruß am Briefende"],
  ["LIED", "Davon kann man eins singen, wenn man Erfahrung hat", "Song auf Deutsch"],
  ["LOCH", "Hat der Käse und manchmal die Socke", "Damit beginnt Golf"],
  ["LUFT", "Ist raus, wenn die Motivation fehlt", "Atmen wir ein und aus"],
  ["LUPE", "Werkzeug von Sherlock Holmes", "Nimmt man etwas unter die, prüft man genau"],
  ["MANN", "Ein …, ein Wort", "Kerl"],
  ["MEHL", "Weißes Pulver aus der Mühle", "Type 405 zum Backen"],
  ["MILD", "Wie Wetter im Frühling", "Wie ein Käse ohne Schärfe"],
  ["MUND", "Nimmt man sich nicht den …, wenn man frei redet", "Sagt beim Arzt: Ah"],
  ["NASE", "Läuft bei Schnupfen", "Darauf sitzt die Brille"],
  ["NEID", "Gelb vor …", "Gefühl, wenn andere mehr haben"],
  ["NEST", "Daraus fliegen Küken aus", "Kuscheliges Zuhause"],
  ["NETT", "Freundlich, aber ohne Begeisterung: ganz …", "Freundlich, sympathisch"],
  ["NETZ", "Tennisball, der hängenbleibt, landet im …", "Kurzes Wort fürs Internet"],
  ["NOTE", "Eins bis sechs in der Schule", "Do, Re, Mi"],
  ["NUSS", "Harte zu knacken: schwierige Aufgabe", "Haselnuss, Walnuss oder Erdnuss"],
  ["OBST", "Kommt beim Smoothie in den Mixer", "Äpfel, Birnen und Co."],
  ["OPER", "Bühnenkunst mit Arien", "Das Phantom spukt darin"],
  ["PAAR", "Zwei Socken", "Wird beim Ja-Wort zum Ehe…"],
  ["PARK", "Grüne Lunge der Stadt", "Englischer Garten in München ist einer"],
  ["PASS", "Reisedokument", "Gebirgsübergang"],
  ["PECH", "Schwarzer Kater, der von links kommt, bringt …", "Gegenteil von Glück"],
  ["PILZ", "Steinpilz oder Fliegen…", "Wächst nach dem Regen im Wald"],
  ["POOL", "Schwimmbecken im Garten", "Billardvariante"],
  ["QUIZ", "Kneipenabend mit Fragen", "Wer wird Millionär? ist eins"],
  ["RABE", "Schwarzer Vogel, der als sehr klug gilt", "Unrühmlicher Elternteil: … mutter"],
  ["RAUM", "Zimmer", "Weiter … im All"],
  ["REIF", "Wie eine Banane ohne Grün", "Frostkristalle auf dem Auto"],
  ["RIND", "Liefert Steaks und Milch", "Tier für Burger-Patties"],
  ["RING", "Wird beim Antrag überreicht", "Herr der Ringe: „Ein … sie zu knechten“"],
  ["ROCK", "Musik mit E-Gitarre", "Kleidungsstück, Mini- oder Maxi-"],
  ["RUHE", "Kommt vor dem Sturm", "Wird in der Bibliothek erbeten"],
  ["RUND", "Läuft, wenn alles klappt", "Wie eine Pizza"],
  ["SACK", "Darin steckt die Katze", "Große Tüte für Kartoffeln"],
  ["SAND", "Wird in die Augen gestreut", "Baustoff für Burgen am Strand"],
  ["SATT", "Wie man nach dem Buffet ist", "Hat man etwas, wenn man genug davon hat"],
  ["SEIL", "Damit sichert man sich beim Klettern", "Zum Springen auf dem Schulhof"],
  ["SINN", "Wird im Leben gesucht", "Sehen, Hören, Riechen, Schmecken, Tasten – je einer"],
  ["SOHN", "Junior der Familie", "Verlorener … aus dem Gleichnis"],
  ["SOJA", "Bohne für Tofu und Drinks", "Sauce aus Asien"],
  ["SPUR", "Hinterlässt der Täter", "Fahrstreifen auf der Autobahn"],
  ["STAR", "Hat einen Stern auf dem Walk of Fame", "Singvogel – oder Augenkrankheit"],
  ["TANZ", "Walzer ist einer", "Ums goldene Kalb …"],
  ["TEAM", "Toll, ein anderer macht's – Spruch über das hier", "Mannschaft"],
  ["TEIG", "Wird geknetet und darf gehen", "Pizza-Grundlage vor dem Ofen"],
  ["TEIL", "Puzzle besteht aus vielen", "Stück vom Ganzen"],
  ["TEST", "Schnell-… mit zwei Strichen", "Prüfung, Probe"],
  ["TIEF", "Schlechtwettergebiet auf der Karte", "Wie das Wasser am Zehner"],
  ["TIER", "Ein hohes …: wichtige Person, ironisch", "Haus… mit Futternapf"],
  ["TIPP", "Ratschlag – oder Wette beim Lotto", "Insider-Hinweis"],
  ["TOLL", "Super, großartig", "Wahnsinnig gut"],
  ["TOUR", "Konzertreise einer Band", "Rundfahrt, z. B. de France"],
  ["TREU", "Wie ein Hund zu seinem Menschen", "Loyal"],
  ["TRIO", "Drei auf einer Bühne", "Die drei ??? sind eins"],
  ["TUBE", "Zahnpasta-Verpackung", "Englisch für Londoner U-Bahn"],
  ["TURM", "Schachfigur, die nur gerade zieht", "Eiffel… in Paris"],
  ["UFER", "Ans andere will man, wenn man die Seiten wechselt", "Rand eines Sees"],
  ["VASE", "Darin welken Schnittblumen", "Blumen-Behälter auf dem Tisch"],
  ["VOLK", "Hat bei der Wahl das letzte Wort", "Bienen leben in einem"],
  ["WACH", "So hält Kaffee einen", "Nicht mehr im Bett, sondern bei Bewusstsein"],
  ["WAHL", "Qual laut Sprichwort", "Kreuz im Kästchen alle vier Jahre"],
  ["WAND", "Hier hängt der Fernseher", "Kletter… in der Halle"],
  ["WARE", "Wird im Laden angeboten", "Gut, das gehandelt wird"],
  ["WEIT", "Weg zum Ziel, wenn's dauert", "Wie Hosen, die locker sitzen"],
  ["WELT", "Rund-Reisende umrunden sie", "Wird am liebsten gerettet"],
  ["WERT", "Steht auf dem Preisschild, aber nicht immer richtig", "Lohnenswert"],
  ["WILD", "Reh und Hirsch auf der Speisekarte", "Ungezähmt"],
  ["WOLF", "Fleisch-…: Küchengerät für Hack", "Heult den Mond an"],
  ["WORT", "Davon sucht man in diesem Rätsel viele", "Wird gehalten, wenn man verspricht"],
  ["WURM", "Steckt im Apfel – oder im Computer", "Ohr…: Lied, das nicht mehr rausgeht"],
  ["ZAHL", "Gegenstück von Kopf beim Münzwurf", "Ziffernkombination"],
  ["ZAHN", "Die Fee bringt dafür Geld", "Wird der Zeit nachgesagt, dass er nagt"],
  ["ZART", "Wie ein gutes Steak", "Empfindlich, sanft"],
  ["ZAUN", "Darüber unterhalten sich Nachbarn", "Gartengrenze"],
  ["ZEIT", "Davon hat man nie genug", "Wird totgeschlagen, wenn's langweilig ist"],
  ["ZOFF", "Ärger mit den Nachbarn", "Streit, umgangssprachlich"],
  ["ZOLL", "Kontrolliert an der Grenze", "Längenmaß für Bildschirmdiagonalen"],

  // ---------- 5 Buchstaben ----------
  ["AZUBI", "Ist im ersten Lehrjahr", "Lehrling, kurz"],
  ["BIRNE", "Obst – und umgangssprachlich der Kopf", "Glüh… von früher"],
  ["BLATT", "Fällt im Herbst", "Wendet sich, wenn sich die Lage ändert"],
  ["BLASS", "So sieht man nach dem Winter aus", "Farblos"],
  ["BLIND", "Date, bei dem man sich nicht kennt", "Ohne Sehvermögen"],
  ["DEICH", "Schützt Nordfriesland vor der Flut", "Darauf grasen Schafe an der Küste"],
  ["DRAHT", "Heißer … zwischen Washington und Moskau", "Dünner Metallfaden"],
  ["DUMM", "So kann man sich fühlen, wenn man nicht weiterkommt", "Wie eine Frage, die es angeblich nicht gibt"],
  ["EIMER", "Im …: kaputt, umgangssprachlich", "Behälter fürs Putzwasser"],
  ["EILIG", "Wie ein Paket mit Express", "In Zeitnot"],
  ["ERNTE", "Lohn der Gartenarbeit", "Wird im Herbst eingefahren"],
  ["ESSEN", "Stadt im Ruhrgebiet mit Zeche Zollverein", "Mahlzeit"],
  ["ETAGE", "Stockwerk", "Beletage ist die schönste"],
  ["FADEN", "Verliert man, wenn man den Gedanken vergisst", "Garn zum Nähen"],
  ["FARBE", "Bekennt man, wenn man sich festlegt", "Rot, Blau oder Grün"],
  ["FEDER", "Schreibgerät vergangener Zeit", "Leicht wie eine …"],
  ["FISCH", "Stumm wie ein …", "Lebt im Aquarium"],
  ["FLACH", "Wie ein Witz ohne Pointe", "Wie die Erde laut Verschwörungstheorie"],
  ["GEIST", "Spukt im Schloss", "Verstand, Intellekt"],
  ["GEHEN", "Zu Fuß unterwegs sein", "Wie es einem …? – Frage zur Begrüßung"],
  ["GLATT", "Wie Straßen bei Blitzeis", "Faltenfrei"],
  ["GRUND", "Ursache", "Liegt am Boden des Sees"],
  ["HAFEN", "Hier legen Schiffe an", "Hamburgs Tor zur Welt"],
  ["KLEID", "Das kleine Schwarze ist eins", "Macht Leute, sagt das Sprichwort (Mz.: …er)"],
  ["KRANK", "Mit gelbem Schein zu Hause", "Fühlt man sich mit Fieber"],
  ["KREIS", "Hat keinen Anfang und kein Ende", "Freundes…"],
  ["KRUMM", "Wie eine Banane", "Gebogen"],
  ["LAMPE", "Hat einen Schirm, aber nie Regen", "Leuchte"],
  ["LESEN", "Macht man mit Büchern und Gedanken", "Weinernte"],
  ["LICHT", "Geht einem auf, wenn man versteht", "Am Ende des Tunnels"],
  ["LINIE", "In erster …", "Busnummer"],
  ["LÖWE", "Simba ist einer", "König der Tiere"],
  ["MALEN", "Was man mit Pinsel und Leinwand macht", "Zahlen… als Hobby"],
  ["MAPPE", "Bewerbungs…", "Tasche für Unterlagen"],
  ["MARKT", "Wochen… mit Gemüse", "Angebot und Nachfrage treffen sich hier"],
  ["MAUER", "Fiel 1989 in Berlin", "Steinwand"],
  ["MOTOR", "Herz des Autos", "Treibende Kraft"],
  ["MUTIG", "Wer den Sprung wagt, ist …", "Furchtlos"],
  ["NADEL", "Im Heuhaufen schwer zu finden", "Hat ein Öhr"],
  ["NAGEL", "Wird auf den Kopf getroffen, wenn man genau richtig liegt", "Lackiert man im Studio"],
  ["PLATT", "Wie ein Reifen ohne Luft", "Norddeutsche Mundart"],
  ["PLATZ", "Wird an der Bar reserviert", "Freifläche in der Stadt"],
  ["PREIS", "Was etwas kostet", "Bekommt der Gewinner"],
  ["RATEN", "Tut man hier manchmal", "Teilzahlungen"],
  ["REDEN", "Ist Silber, Schweigen ist Gold", "Werden auf Hochzeiten gehalten (Mz.)"],
  ["REICH", "Wie Dagobert Duck", "Kaiser…"],
  ["ROLLE", "Klopapier im Hamsterkauf", "Spielt keine, wenn's egal ist"],
  ["SAGEN", "Hat man nichts zu, wenn man unwichtig ist", "Äußern"],
  ["SCHAF", "Zählt man beim Einschlafen", "Schwarzes in der Familie"],
  ["SEGEL", "Werden gestrichen, wenn man aufgibt", "Fängt den Wind ein"],
  ["SEHEN", "Lernt man mit dem Sehtest einschätzen", "Wahrnehmen mit den Augen"],
  ["SEIFE", "Schäumt am Waschbecken", "Oper aus Amerika: Daily-…"],
  ["SEITE", "Hat jede Medaille zwei", "Website auf Deutsch"],
  ["STARK", "Jugendsprachlich: richtig gut", "Kräftig"],
  ["STEIN", "Fällt einem vom Herzen", "Am Brett beim Spiel „Vier gewinnt“"],
  ["STILL", "Wasser ohne Sprudel", "Ruhig"],
  ["STOFF", "Vorhang… oder Lern…", "Material für Kleidung"],
  ["STUHL", "Darauf sitzt man im Büro", "Wird einem vor die Tür gestellt"],
  ["STUMM", "Wie ein Handy im Kino", "Wie ein Fisch"],
  ["TINTE", "In der … sitzen: in der Klemme", "Füllerflüssigkeit"],
  ["TISCH", "Wird beim Streiten auf den gehauen", "Esszimmermöbel"],
  ["TOAST", "Brot aus dem Röster", "Trinkspruch"],
  ["WEICH", "Wie ein Kissen", "Wie ein gekochtes Ei nach vier Minuten"],
  ["WOLKE", "Auf …sieben schweben", "Schäfchen am Himmel"],
  ["WURST", "Ist es einem, wenn es egal ist", "Liegt auf dem Grill"],
  ["ZWERG", "Davon gibt es sieben bei Schneewittchen", "Garten… mit roter Mütze"],

  // ---------- Verben ----------
  ["LIKEN", "Herzchen unter einen Post setzen", "Daumen hoch auf Social Media"],
  ["POSTEN", "Etwas auf Social Media veröffentlichen", "Wachdienst – oder Stelle im Job"],
  ["TEILEN", "Durch zwei rechnen – oder einen Link weiterleiten", "Mit Freunden abgeben"],
  ["GOOGELN", "Im Netz nachschlagen", "Seit 2004 im Duden: Suchmaschine benutzen"],
  ["TIPPEN", "Auf dem Display schreiben", "Beim Lotto die Zahlen ankreuzen"],
  ["SCROLLEN", "Endlos durch den Feed wischen", "Am Mausrad drehen"],
  ["CHATTEN", "Per Text plaudern", "Mit der KI ein Gespräch führen"],
  ["FLIRTEN", "Jemandem schöne Augen machen", "Anbaggern, auf charmante Art"],
  ["SHOPPEN", "Einkaufsbummel als Hobby", "Online in den Warenkorb legen"],
  ["CHECKEN", "Kapieren, verstehen", "Mails kurz kontrollieren"],
  ["JOBBEN", "Neben dem Studium Geld verdienen", "Kellnern in den Semesterferien"],
  ["PENNEN", "Umgangssprachlich schlafen", "Im Unterricht wegdösen"],
  ["NERVEN", "Auf den Keks gehen", "Liegen blank bei Stress"],
  ["MECKERN", "Wie eine Ziege – oder ein Nörgler", "Rummotzen"],
  ["LÄSTERN", "Hinter dem Rücken über jemanden reden", "Tratschen, aber gemein"],
  ["KUSCHELN", "Mit Decke und Partner auf dem Sofa", "Sich aneinanderschmiegen"],
  ["HOFFEN", "Stirbt zuletzt", "Auf ein gutes Ende setzen"],
  ["WARTEN", "Tut man auf die Bahn", "Den Wagen in der Werkstatt pflegen"],
  ["RUFEN", "Laut nach jemandem verlangen", "Ein Taxi …"],
  ["HUPEN", "Im Stau Dampf ablassen", "Mit dem Lenkrad laut werden"],
  ["PARKEN", "Mit dem Auto in die Lücke", "Geld auf dem Tagesgeldkonto …"],
  ["TANKEN", "An der Zapfsäule nachfüllen", "Kraft schöpfen im Urlaub"],
  ["BUCHEN", "Flug oder Hotel reservieren", "Einen Betrag aufs Konto …"],
  ["PACKEN", "Koffer füllen", "Schaffen, bewältigen: Wir … das!"],
  ["SPÜLEN", "Nach dem Essen mit Schwamm und Bürste", "Toilette betätigen"],
  ["WASCHEN", "Hand … die andere", "Mit Wasser und Seife reinigen"],
  ["FÖHNEN", "Haare mit warmer Luft trocknen", "Stylingschritt nach dem Haarewaschen"],
  ["BÜGELN", "Falten aus dem Hemd entfernen", "Im Sport: haushoch besiegen"],
  ["KOCHEN", "Vor Wut … wie Wasser im Topf", "Am Herd stehen"],
  ["BACKEN", "Plätzchen im Advent herstellen", "Im Ofen braun werden lassen"],
  ["LERNEN", "Vor der Prüfung pauken", "Nie aus, sagt man"],
  ["LIEGEN", "In der Sonne am Strand", "Bleibt etwas, wenn man es vergisst"],
  ["SITZEN", "Bleiben in der Schule: Ehrenrunde", "Auf dem Stuhl Platz genommen haben"],
  ["STEHEN", "Auf etwas …: es mögen", "Im Stau nicht vorankommen"],
  ["LAUFEN", "Wie die Nase bei Schnupfen", "Joggen, Rennen, Gehen"],
  ["RENNEN", "Formel-1-Veranstaltung", "Sehr schnell laufen"],
  ["ZAHLEN", "An der Kasse bezahlen", "Ziffern"],
  ["ZÄHLEN", "Bis drei …", "Schafe beim Einschlafen …"],
  ["SINGEN", "Unter der Dusche oder beim Karaoke", "Ein Lied davon …"],
  ["TANZEN", "Aus der Reihe …", "Sich zur Musik bewegen"],
  ["TRINKEN", "Zwei Liter Wasser am Tag soll man …", "Prosten und anstoßen"],
  ["WANDERN", "Mit Rucksack über Berg und Tal", "Hobby, das bei Jüngeren gerade wieder in ist"],
  ["TRÄUMEN", "Mit offenen Augen in den Tag …", "Im Schlaf Bilder sehen"],
  ["FEIERN", "Die Feste … wie sie fallen", "Partymachen"],
  ["SPAREN", "Für den Urlaub zurücklegen", "Am falschen Ende …"],
  ["KAUFEN", "Im Laden oder online etwas erwerben", "Abnehmen, glauben: Das … ich dir nicht ab"],
  ["LADEN", "Akku auffüllen", "Geschäft – oder ein Programm starten"],
  ["ANGELN", "Mit Rute am See sitzen", "Sich einen Partner …"],
  ["GIESSEN", "Den Balkon im Sommer versorgen", "Stadt in Hessen mit Uni"],
  ["NIESEN", "Hatschi!", "Danach sagt man: Gesundheit!"],
  ["HUSTEN", "Kratzt im Hals bei Erkältung", "Jemandem etwas …: ablehnen"],
  ["LÄCHELN", "Bitte … für das Foto!", "Freundlich die Mundwinkel heben"],
  ["WINKEN", "Mit der Hand grüßen", "Dem Kellner Zeichen geben"],
  ["KLOPFEN", "An die Tür pochen", "Auf Holz …, damit nichts schiefgeht"],
  ["KLINGELN", "An der Haustür drücken", "Lassen die Kassen, wenn das Geschäft brummt"],
  ["SCHREIEN", "Ist zum …, wenn's sehr lustig ist", "Sehr laut rufen"],
  ["FLÜSTERN", "Stille Post funktioniert so", "Ganz leise sprechen"],
  ["STREITEN", "Wenn zwei sich …, freut sich der Dritte", "Sich in die Haare kriegen"],
  ["HELFEN", "Jemandem unter die Arme greifen", "Was tun, wenn nichts mehr …?"],
  ["SCHENKEN", "Zum Geburtstag etwas überreichen", "Sich nichts …: hart kämpfen"],
  ["ZIEHEN", "Steht an der Tür, wenn man drückt", "Beim Schach einen Zug machen"],
  ["DRÜCKEN", "Daumen … für Glück", "Steht an der Tür, wenn man zieht"],
  ["FAHREN", "Mit Auto, Rad oder Bahn unterwegs sein", "Aus der Haut …"],
  ["FLIEGEN", "Mit Ryanair nach Mallorca", "Aus dem Job rausgeworfen werden, salopp"],
  ["SCHWITZEN", "In der Sauna gewollt, im Bewerbungsgespräch nicht", "Transpirieren"],
  ["FRIEREN", "Wie ein Schneider …", "Bibbern vor Kälte"],

  // ---------- Adjektive ----------
  ["DICK", "Mit jemandem durch … und dünn gehen", "Wie ein Wälzer im Bücherregal"],
  ["DÜNN", "Wie die Luft auf dem Mount Everest", "Wie Fäden aus Spaghetti"],
  ["DUNKEL", "Wie ein Zimmer im Blackout", "Im …n tappen: keine Ahnung haben"],
  ["GROB", "Wie Schleifpapier mit kleiner Körnung", "Ungefähr: … geschätzt"],
  ["HOHL", "Wie ein Schokoladen-Osterhase", "Wie leere Phrasen"],
  ["LAHM", "Wie das WLAN im Zug", "Öde, schwunglos"],
  ["SCHIEF", "Wie der Turm von Pisa", "Läuft etwas, wenn's danebengeht"],
  ["SCHLAU", "Smart, gewitzt", "Wie ein Fuchs im Märchen"],
  ["SCHICK", "Wie man sich zur Hochzeit macht", "Elegant"],
  ["STOLZ", "Wie Eltern bei der Abifeier", "Wie ein Pfau"],
  ["ZAHM", "Wie ein Haustier", "Gezähmt"],
  ["ZÄH", "Wie ein Gummisteak", "Wie ein Montag, der nicht vorbeigeht"],
  ["BRAV", "Wie ein Kind, das Geschenke will", "Artig"],
  ["CHAOTISCH", "Wie der Schreibtisch vor der Deadline", "Völlig durcheinander"],
  ["PEINLICH", "Wie der Papa auf der Tanzfläche", "Zum Fremdschämen"],
  ["ENTSPANNT", "Wie man im Urlaub sein will", "Locker, gelassen, tiefenentspannt"],
  ["GENERVT", "Wie man im Stau ist", "Mit den Nerven am Ende, leicht gereizt"],
  ["HUNGRIG", "Wie man nach dem Sport ist", "Mit knurrendem Magen"],
  ["DURSTIG", "Wie man in der Wüste ist", "Lechzend nach einem Getränk"],
  ["WÜTEND", "Auf hundertachtzig", "Stinksauer"],
  ["TRAURIG", "Wie man beim Ende von „Titanic“ ist", "Bedrückt"],
  ["FRÖHLICH", "… Weihnacht überall", "Gut gelaunt"],
  ["SAUBER", "Wie das Bad nach dem Frühjahrsputz", "Jugendsprachlich-bayerisch: Super!"],
  ["DRECKIG", "Wie Gummistiefel nach dem Festival", "Verschmutzt"],
  ["NERVIG", "Wie Werbung vor dem Video", "Anstrengend, lästig"],
  ["WINZIG", "Wie die Schrift in den AGB", "Mini"],
  ["RIESIG", "Wie ein Kreuzfahrtschiff", "Gigantisch"],
  ["TROCKEN", "Wie britischer Humor", "Ohne Alkohol: wieder … sein"],
  ["FRISCH", "Wie Brötchen am Morgen", "Wie die Luft nach dem Gewitter"],
  ["BITTER", "Wie eine Niederlage in der Nachspielzeit", "Wie dunkle Schokolade"],
  ["SALZIG", "Wie Meerwasser", "Wie Popcorn im Kino, nicht süß"],
  ["GESUND", "Wie Gemüse angeblich ist", "Heil, fit"],
  ["SICHER", "Wie ein gutes Passwort", "Bestimmt!"],
  ["LEDIG", "Familienstand vor der Hochzeit", "Unverheiratet"],
  ["MODERN", "Zeitgemäß", "Wie man dieses Rätsel finden soll"],
  ["GRATIS", "Wie die Probe im Supermarkt", "Umsonst"],
  ["BILLIG", "Wie ein Plagiat vom Markt", "Spottgünstig, oft minderwertig"],
  ["SELTEN", "Wie ein pünktlicher Zug, böse gesagt", "Rar"],
  ["SPÄT", "Wie es nach Mitternacht ist", "Kommt, wer zu … kommt, den bestraft das Leben"],
  ["FRÜH", "Wie der Vogel, der den Wurm fängt", "Bei Tagesanbruch"],
  ["BEREIT", "Startklar", "Auf die Plätze, fertig, …"],
  ["FERTIG", "Wie man nach einem langen Tag ist", "Erledigt"],
  ["WICHTIG", "Wie sich manche gern machen", "Bedeutsam"],
  ["RICHTIG", "Was hoffentlich deine Antworten sind", "Korrekt"],
  ["FALSCH", "Wie ein Fünfzig-Euro-Schein aus dem Drucker", "Inkorrekt"],
  ["GERADE", "Wie eine Linie mit dem Lineal", "Zahl wie 2, 4 oder 6"],
  ["OFFEN", "Wie eine Tür, die einlädt", "Ehrlich, ungezwungen"],
  ["PRIVAT", "Wie ein Instagram-Profil mit Schloss", "Nicht öffentlich"],
  ["DIGITAL", "Wie Behördengänge sein sollten", "In Einsen und Nullen"],
  ["ANALOG", "Wie Schallplatten und Papierkalender", "Old School statt digital"],
  ["ONLINE", "Mit grünem Punkt im Chat", "Im Netz unterwegs"],
  ["OFFLINE", "Wie man im Funkloch ist", "Ohne Netz"],

  // ---------- Weitere Alltagsnomen ----------
  ["ANKER", "Wird gelichtet, wenn das Schiff ablegt", "Fester Halt, auch im übertragenen Sinn"],
  ["APRIL", "Monat, der macht, was er will", "Monat der Scherze am Ersten"],
  ["ARBEIT", "Erst die …, dann das Vergnügen", "Job"],
  ["ÄRGER", "Was man mit dem Finanzamt nicht will", "Zoff, Stress"],
  ["BADEHOSE", "Liegt nach dem Freibad nass im Rucksack", "Shorts zum Schwimmen"],
  ["BECHER", "Coffee-to-go-Gefäß", "Joghurt-Verpackung"],
  ["BESEN", "Neue kehren gut", "Fortbewegungsmittel der Hexe"],
  ["BLITZ", "Fotografen nutzen ihn bei schlechtem Licht", "Zuckt beim Gewitter"],
  ["BODEN", "Ist man am …, wenn man erschöpft ist", "Parkett oder Laminat"],
  ["BOHNE", "Kaffee… oder Jelly-Belly", "Nicht die …: überhaupt nicht"],
  ["BRIEFMARKE", "Klebt oben rechts auf dem Umschlag", "Sammelobjekt der Philatelisten"],
  ["BÜHNE", "Bretter, die die Welt bedeuten", "Darauf spielt die Band"],
  ["DECKEL", "Jeder Topf findet seinen", "Bierfilz, auf dem man anschreibt"],
  ["DUSCHVORHANG", "Klebt beim Duschen gern am Bein", "Plastik mit Muster vor der Wanne"],
  ["EINLADUNG", "Kommt per Messenger zur Geburtstagsparty", "Bitte, vorbeizukommen"],
  ["ERBSE", "Die Prinzessin spürte sie durch zwanzig Matratzen", "Grünes Kügelchen aus der Schote"],
  ["FAHRSTUHL", "Hier wird gern Smalltalk vermieden", "Lift"],
  ["FERNBEDIENUNG", "Verschwindet ständig in der Sofaritze"],
  ["FLECK", "Ketchup auf dem weißen Shirt", "Blauer … am Schienbein"],
  ["FREIZEIT", "Das, wofür man arbeitet", "Zeit nach Feierabend"],
  ["GABE", "Talent – oder Geschenk", "Spende in der Kollekte"],
  ["GLAS", "Ist halb voll oder halb leer", "Durchsichtiger Werkstoff"],
  ["GURT", "Klickt im Auto vor dem Losfahren", "Den … enger schnallen: sparen"],
  ["HAMMER", "Jugendsprachlich: der Wahnsinn!", "Werkzeug für den Nagel"],
  ["HEIZUNG", "Wird im Oktober wieder aufgedreht", "Wärmt mit Rippen am Fenster"],
  ["HÖHLE", "Hier wohnte der Steinzeitmensch", "Löwen…: gefährlicher Ort"],
  ["KÄFIG", "Goldener … – Luxus ohne Freiheit", "Wohnung von Wellensittich und Hamster"],
  ["KANNE", "Gießt man im Garten", "Es gießt wie aus …n"],
  ["KARTE", "Rote im Fußball bedeutet Platzverweis", "Speise… oder Fahr…"],
  ["KELLER", "Hier steht die Waschmaschine oft", "Partyraum im Untergeschoss"],
  ["KERZE", "Wird auf der Torte ausgepustet", "Steht im Advent im Kranz"],
  ["KETTE", "Springt beim Fahrrad gern ab", "Hals… mit Anhänger"],
  ["KIOSK", "Späti, Büdchen, Trinkhalle", "Verkauft Zeitungen und Lakritz"],
  ["KISTE", "Getränke… zum Schleppen", "Alte … : Klapperauto"],
  ["KNOPF", "Fällt vom Hemd ab", "Wird gedrückt – z. B. der rote"],
  ["KOFFEIN", "Wachmacher im Espresso", "Steckt in Energydrinks und Cola"],
  ["KRAFT", "Wird im Studio aufgebaut", "Stärke"],
  ["KRONE", "Trägt der König", "Zahnersatz aus Keramik"],
  ["KÜSTE", "Ost… oder Nord…", "Hier treffen Land und Meer"],
  ["LÄRM", "Viel … um nichts", "Krach von der Baustelle"],
  ["LEITER", "Steigt man hoch zum Dachboden", "Chef einer Abteilung"],
  ["LISTE", "To-do-… mit Häkchen", "Steht man auf der Gäste…, kommt man rein"],
  ["LÜGE", "Hat kurze Beine", "Pinocchios Nase wächst bei jeder"],
  ["MAGEN", "Knurrt bei Hunger", "Liebe geht durch den …"],
  ["MATTE", "Unterlage beim Yoga", "Fußabtreter vor der Tür"],
  ["MEINUNG", "Hat jeder im Netz zu allem", "Ansicht, Standpunkt"],
  ["MINUTE", "Gibt's beim Kochen von Eiern meist vier oder zehn", "Zeitspanne mit 60 Sekunden"],
  ["MITTE", "Goldene … – der Kompromiss", "Berliner Bezirk"],
  ["MÖBEL", "Werden bei Ikea selbst zusammengebaut", "Sofa, Regal, Bett"],
  ["MONAT", "Ende des …: wenn das Konto leer ist", "Hat 28 bis 31 Tage"],
  ["NARBE", "Erinnerung an eine Verletzung", "Harry Potters hat Blitzform"],
  ["NEFFE", "Tick, Trick und Track: Jeder ist Donalds …", "Sohn der Schwester"],
  ["NICHTE", "Tochter des Bruders", "Tochter der Schwester"],
  ["NOTIZ", "Haftzettel am Bildschirm", "Kurze Aufzeichnung"],
  ["OASE", "Grüner Fleck in der Wüste", "Ruhepol im Trubel"],
  ["ONKEL", "Dagobert ist der von Donald", "Bruder von Mama oder Papa"],
  ["TANTE", "Schwester von Mama oder Papa", "…-Emma-Laden: kleiner Krämerladen"],
  ["PALME", "Bringt einen auf die …: macht wütend", "Baum am Karibikstrand"],
  ["PANNE", "Warnweste und Warndreieck sind dann gefragt", "Technischer Ausfall"],
  ["PAPIER", "Ist geduldig, sagt man", "Wird im Drucker gestaut"],
  ["PERLE", "Wächst in der Muschel", "Wird vor die Säue geworfen"],
  ["PILOT", "Sitzt im Cockpit", "Erste Folge einer Serie"],
  ["PINSEL", "Malerwerkzeug", "Hat Borsten und kommt in den Farbeimer"],
  ["POSTER", "Hängt im Jugendzimmer an der Wand", "Großformatiger Druck"],
  ["PUPPE", "Spielzeug mit Kleidern", "Bis in die …n schlafen"],
  ["QUELLE", "Wird im Referat angegeben", "Hier entspringt der Fluss"],
  ["RASEN", "Fußballfeld-Belag", "Mit hohem Tempo fahren"],
  ["RAKETE", "Startet an Silvester – oder zum Mond", "Elon Musks Spaceship ist eine"],
  ["REGAL", "Billy ist das berühmteste", "Möbel für Bücher"],
  ["REIFEN", "Wird im Herbst gewechselt", "Gummi um die Felge"],
  ["RENTE", "Wird mit 67 fällig", "Ruhestandsgeld"],
  ["ROBOTER", "Staubsauger, der allein fährt", "R2-D2 ist einer"],
  ["SAHNE", "Topping auf dem Kakao", "Erste …: allerbeste Qualität"],
  ["SCHAUM", "Krone auf dem Bier", "Wird geschlagen, wenn jemand große Reden schwingt"],
  ["SCHERE", "Schneidet Papier", "Stein, Papier, …"],
  ["SCHIFF", "Kreuzfahrt-… – schwimmende Kleinstadt", "Titanic war eins"],
  ["SCHILD", "Steht am Straßenrand", "Hat der Ritter in der Hand"],
  ["SCHLOSS", "Neuschwanstein ist eins", "Wird mit dem Schlüssel geöffnet"],
  ["SCHMERZ", "Tut weh", "Geteilter ist halber"],
  ["SCHRANK", "Muss man bei Narnia durchqueren", "Kleider…"],
  ["SCHULD", "Haben immer die anderen", "Verantwortung für einen Fehler"],
  ["SEKUNDE", "Kürzeste Zeiteinheit auf der Stoppuhr", "Einen Moment!"],
  ["SENDUNG", "Läuft im Fernsehen", "Wird per Kurier verfolgt"],
  ["SPIEGEL", "Fragt im Märchen nach der Schönsten", "Darin macht man Selfies im Bad"],
  ["SPRAY", "Deo aus der Dose", "Graffiti-Werkzeug"],
  ["STECKER", "Wird gezogen, wenn Schluss ist", "Passt in die Steckdose"],
  ["STEMPEL", "Behörden lieben ihn", "Hinterlässt einen Abdruck auf dem Formular"],
  ["STREIT", "Kommt in den besten Familien vor", "Zoff, Zank"],
  ["STROM", "Kommt aus der Steckdose", "Mit dem … schwimmen"],
  ["STUNDE", "Wird zur Sommerzeit vorgestellt", "Hat 60 Minuten"],
  ["SUCHE", "Funktion mit Lupen-Symbol", "Fahndung"],
  ["TABLETTE", "Wird mit Wasser geschluckt", "Pille"],
  ["TASCHE", "Hat fast jede Hose – nur nie genug", "Steckt man jemanden in die, ist man ihm überlegen"],
  ["TOCHTER", "Kind, das später Mama werden kann", "Mädchen der Familie"],
  ["TONNE", "Gelbe, blaue oder braune", "1000 Kilogramm"],
  ["TRAUBE", "Ist sauer, wenn sie zu hoch hängt", "Beere am Weinstock"],
  ["TRÄNE", "Rollt bei Kitschfilmen", "Krokodils…: falsches Mitgefühl"],
  ["TÜTE", "Kommt nicht in die …: auf keinen Fall", "Papier statt Plastik an der Kasse"],
  ["UNFALL", "Blechschaden auf der Kreuzung", "Ungewolltes Missgeschick"],
  ["VATER", "Wird am Himmelfahrtstag mit Bollerwagen gefeiert", "Papa"],
  ["MUTTER", "Hat im Mai ihren eigenen Tag", "Gegenstück zur Schraube"],
  ["VORHANG", "Fällt am Ende des Theaterstücks", "Hängt vorm Fenster"],
  ["WAFFEL", "Mit Puderzucker und Kirschen", "Eis…: Hörnchen"],
  ["WAGEN", "Einkaufs… mit Euro-Chip", "Riskieren, sich trauen"],
  ["WÄRME", "Spendet die Heizung", "Herzlichkeit"],
  ["WECHSEL", "Reifen… im Herbst", "Veränderung"],
  ["WESTE", "Weiße … haben: unschuldig sein", "Ärmelloses Oberteil"],
  ["WIESE", "Hier wird im September in München gefeiert", "Grasfläche"],
  ["WITZ", "Hat eine Pointe", "Das ist doch ein …! – kaum zu glauben"],
  ["WOCHE", "Von Montag bis Sonntag", "Flitter…: nach der Hochzeit"],
  ["WÜSTE", "Hier gibt's Fata Morganas", "Jemanden in die … schicken: entlassen"],
  ["ZETTEL", "Wird an den Kühlschrank geklebt", "Einkaufs…"],
  ["ZIMMER", "Hotel… mit Minibar", "Kinder… mit Spielzeug"],
  ["ZUKUNFT", "Wird von Wahrsagern vorhergesagt", "Was vor uns liegt"],
);
