// Stapel 4: weitere Mischung, Fokus auf 3–6 Buchstaben (bewusst unsortiert)
WORDS.push(
  ["DAU", "Dümmster anzunehmender User (Abk.)"],
  ["ZEPTER", "Hat der König in der Hand"],
  ["AIRFRYER", "Heißluftfritteuse, englisch"],
  ["BOJE", "Schwimmt im Hafen als Markierung"],
  ["GAU", "Größter anzunehmender Unfall (Abk.)"],
  ["NIXE", "Wassergeist mit Fischschwanz"],
  ["QUARZ", "Mineral in der Uhr"],
  ["ABT", "Chef im Kloster"],
  ["JETLAG", "Müdigkeit nach dem Langstreckenflug"],
  ["KOJE", "Bett auf dem Schiff"],
  ["DEO", "Gegen Schweißgeruch (kurz)"],
  ["THRON", "Sitz des Königs"],
  ["LAVA", "Glühendes Gestein aus dem Vulkan"],
  ["EBER", "Männliches Schwein"],
  ["HUF", "Fuß des Pferdes"],
  ["SPUK", "Gruseliges Treiben von Geistern"],
  ["TAROT", "Kartendeck zum Wahrsagen"],
  ["PEP", "Schwung, Elan"],
  ["DOGE", "Venezianisches Staatsoberhaupt – oder Shiba-Meme"],
  ["KNAST", "Gefängnis, umgangssprachlich"],
  ["VAPE", "E-Zigarette"],
  ["ZAR", "Russischer Herrscher"],
  ["GRAL", "Heiliger Kelch der Artussage"],
  ["MOP", "Wischgerät mit Fransen"],
  ["SALTO", "Überschlag in der Luft"],
  ["EKEL", "Gefühl beim Anblick von Schimmel"],
  ["YEN", "Japanische Währung"],
  ["LIGA", "Spielklasse im Sport"],
  ["SPECK", "Hüftgold – oder Schinken"],
  ["ION", "Geladenes Teilchen"],
  ["WOW", "Ausruf des Staunens"],
  ["PIRAT", "Seeräuber mit Augenklappe"],
  ["ULK", "Spaß, Unfug"],
  ["SMOG", "Dicke Luft über der Großstadt"],
  ["KAP", "Landspitze, wie das der Guten Hoffnung"],
  ["LUV", "Dem Wind zugewandte Seite"],
  ["LEE", "Dem Wind abgewandte Seite"],
  ["MOB", "Wütende Menge"],
  ["SIR", "Britischer Ritter-Titel"],
  ["JOT", "Buchstabe vor K"],
  ["IRE", "Bewohner der Grünen Insel"],
  ["BOA", "Würgeschlange – oder Federschal"],
  ["ALB", "Albtraum-Geist – oder schwäbisches Gebirge"],
  ["FES", "Rote Kappe mit Quaste"],
  ["GEN", "Erbanlage"],
  ["LID", "Klappt beim Blinzeln zu"],
  ["LOT", "Senkblei – oder Neffe Abrahams"],
  ["NOT", "Macht erfinderisch"],
  ["PUR", "Unvermischt, rein"],
  ["ZEH", "Wird gern an der Bettkante gestoßen"],
  ["GAG", "Witziger Einfall"],
  ["EDV", "Elektronische Datenverarbeitung (Abk.)"],
  ["EKG", "Herzstromkurve (Abk.)"],
  ["MRT", "Lauter Röhrenscan im Krankenhaus (Abk.)"],
  ["NEE", "Norddeutsches Nein"],
  ["OHO", "Ausruf der Überraschung"],
  ["DIN", "Norm, nach der Papierformate gehen (Abk.)"],
  ["SUV", "Großer Stadtgeländewagen (Abk.)"],
  ["TAZ", "Berliner Tageszeitung (Abk.)"],
  ["MOD", "Nutzer-Erweiterung für ein Spiel"],
  ["ARAL", "Austrocknender See in Zentralasien – oder Tankstelle"],
  ["BORD", "An … gehen: das Schiff betreten"],
  ["BRUT", "Nachwuchs im Nest – oder sehr trockener Sekt"],
  ["BUDE", "Kleine Wohnung, Studentenzimmer"],
  ["DAMM", "Staumauer"],
  ["DEKO", "Kissen und Kerzen für die Wohnung"],
  ["DOLCH", "Kurze Stichwaffe"],
  ["EDAM", "Holländischer Käse mit roter Rinde"],
  ["EGAL", "Wurst, gleichgültig"],
  ["EMIR", "Fürst am Golf"],
  ["ENKEL", "Kind des eigenen Kindes"],
  ["EPOS", "Heldengedicht, wie die Ilias"],
  ["FELL", "Haarkleid des Hundes"],
  ["FILZ", "Gepresster Wollstoff – oder Vetternwirtschaft"],
  ["FLOH", "Hüpfender Parasit – oder Markt für Trödel"],
  ["FLOP", "Misserfolg an den Kinokassen"],
  ["FLUT", "Gegenstück zur Ebbe"],
  ["FOHLEN", "Junges Pferd"],
  ["FRACK", "Festlicher Anzug mit Schwalbenschwanz"],
  ["GAUL", "Altes Pferd, dem man nicht ins Maul schaut"],
  ["GEIGE", "Spielt die erste … – wer das Sagen hat"],
  ["GEIER", "Aasfresser mit kahlem Hals"],
  ["GIER", "Maßlose Begierde"],
  ["GILDE", "Zunft der Handwerker – oder Clan im Game"],
  ["GLUT", "Rest vom Lagerfeuer"],
  ["GNADE", "Recht, das vor Recht ergehen kann"],
  ["GRAT", "Scharfe Bergkante"],
  ["GRIPS", "Verstand, Köpfchen"],
  ["GROLL", "Heimlicher Ärger"],
  ["HAGEL", "Eiskörner vom Himmel"],
  ["HALDE", "Aufgeschütteter Berg im Ruhrgebiet"],
  ["HALLE", "Großer Raum – oder Stadt an der Saale"],
  ["HANF", "Pflanze für Seile und Joints"],
  ["HAST", "Eile, Überstürzung"],
  ["HECK", "Hinterteil von Auto oder Schiff"],
  ["HEER", "Armee"],
  ["HERDE", "Gruppe von Schafen"],
  ["HIRN", "Denkapparat"],
  ["HUMOR", "Ist, wenn man trotzdem lacht"],
  ["HYDRA", "Vielköpfiges Ungeheuer"],
  ["IKONE", "Heiligenbild – oder Stilvorbild"],
  ["INKA", "Volk von Machu Picchu"],
  ["IMAM", "Vorbeter in der Moschee"],
  ["JAGD", "Schnitzel… mit Zettelchen"],
  ["JOCH", "Last – oder Geschirr für Ochsen"],
  ["KALB", "Junges Rind"],
  ["KANAL", "Künstliche Wasserstraße – oder YouTube-Präsenz"],
  ["KARO", "Spielkartenfarbe – oder Muster"],
  ["KEIL", "Wird zwischen Holz getrieben"],
  ["KELCH", "Geht an einem vorüber, wenn man Glück hat"],
  ["KILT", "Schottenrock"],
  ["KIPPE", "Zigarettenstummel"],
  ["KOBOLD", "Pumuckl ist einer"],
  ["KOMA", "Tiefe Bewusstlosigkeit"],
  ["KRACH", "Lärm – oder Streit"],
  ["KRAM", "Zeug, Plunder"],
  ["KUFE", "Teil des Schlittens"],
  ["KUNST", "Liegt im Auge des Betrachters"],
  ["KUTTE", "Mönchsgewand – oder Rockerweste"],
  ["LACK", "Ist ab, wenn der Glanz verflogen ist"],
  ["LAIE", "Nicht-Fachmann"],
  ["LASSO", "Wurfschlinge des Cowboys"],
  ["LAUNE", "Stimmung"],
  ["LAWINE", "Schneemassen, die ins Tal donnern"],
  ["LEIM", "Kleber für Holz – auf den geht man, wenn man reinfällt"],
  ["LEINE", "Hält den Hund"],
  ["LIMO", "Süße Brause"],
  ["LOGO", "Markenzeichen"],
  ["LOTSE", "Führt Schiffe durch den Hafen"],
  ["LUKE", "Klappe im Schiffsdeck"],
  ["LUNTE", "Zündschnur – riecht man, wenn man etwas ahnt"],
  ["MAUT", "Straßengebühr"],
  ["MEMO", "Kurze Notiz"],
  ["MIENE", "Gesichtsausdruck – gute … zum bösen Spiel"],
  ["MIXER", "Küchengerät für Smoothies"],
  ["MOKKA", "Starker Kaffee"],
  ["MORAL", "Lehre aus der Geschichte"],
  ["MOTTE", "Löchert Pullis im Schrank"],
  ["MUSE", "Küsst den Künstler"],
  ["MUSKEL", "Bizeps ist einer"],
  ["NAPF", "Futterschale fürs Haustier"],
  ["NONNE", "Frau im Kloster"],
  ["NORM", "Regel, Standard"],
  ["NUGAT", "Nussmasse in Pralinen"],
  ["OLIVE", "Steckt im Martini"],
  ["OPIUM", "Mohnsaft – laut Marx fürs Volk"],
  ["ORAKEL", "Weissagung, wie in Delphi"],
  ["ORDEN", "Auszeichnung an der Brust – oder Mönchsgemeinschaft"],
  ["ORGEL", "Königin der Instrumente"],
  ["PAKT", "Bündnis, Abkommen"],
  ["PAPST", "Oberhaupt im Vatikan"],
  ["PATE", "Taufzeuge – oder Mafiaboss im Film"],
  ["PELZ", "Fell als Mantel"],
  ["PILS", "Bier mit Schaumkrone"],
  ["PISTE", "Abfahrt beim Skifahren"],
  ["POKAL", "Siegertrophäe"],
  ["POSSE", "Schwank, lächerliches Theater"],
  ["PRISMA", "Zerlegt Licht in Farben"],
  ["PRUNK", "Protz, Pracht"],
  ["PUDEL", "Hund mit Lockenfrisur – des Pudels Kern"],
  ["PULT", "Rednertisch"],
  ["PUMPE", "Hebt Wasser – oder salopp das Herz"],
  ["QUAL", "Hat man bei der Wahl"],
  ["RAMPE", "Schräge Auffahrt"],
  ["RANG", "Stufe in der Hierarchie"],
  ["RAPS", "Gelbe Felder im Frühling"],
  ["RASUR", "Glatt geschabtes Kinn"],
  ["RAUPE", "Wird zum Schmetterling – Nimmersatt ist eine"],
  ["REBE", "Weinstock"],
  ["REGIE", "Führt der Filmemacher"],
  ["REIM", "Herz auf Schmerz"],
  ["REST", "Was übrig bleibt"],
  ["RIEGEL", "Türsperre – oder Schoko-Snack"],
  ["RIFF", "Korallenbank – oder Gitarrenmotiv"],
  ["RISS", "Spalt in der Wand"],
  ["RODEL", "Schlitten in Bayern"],
  ["RUDER", "Steuert das Boot – oder hilft beim Herumreißen"],
  ["RUINE", "Verfallenes Gemäuer"],
  ["RUNE", "Germanisches Schriftzeichen"],
  ["SAGA", "Isländische Erzählung – oder Filmreihe"],
  ["SAMBA", "Tanz im brasilianischen Karneval"],
  ["SARG", "Letzte Kiste"],
  ["SATIRE", "Darf alles, sagte Tucholsky"],
  ["SAUM", "Rand des Stoffes"],
  ["SEKTE", "Abgespaltene Glaubensgruppe"],
  ["SENAT", "Römischer Rat – oder Hamburger Regierung"],
  ["SERUM", "Impfstoff – oder Hautpflege"],
  ["SIEB", "Hat ein Gedächtnis wie …"],
  ["SIEG", "Gegenstück zur Niederlage"],
  ["SILO", "Getreidespeicher – oder Abteilung, die nicht kommuniziert"],
  ["SIRUP", "Dickflüssiges Süßes"],
  ["SKALA", "Maßeinteilung"],
  ["SKAT", "Kartenspiel mit Reizen"],
  ["SOCKEL", "Fuß der Statue"],
  ["SOLO", "Allein, ohne Band"],
  ["SONDE", "Raumfahrzeug ohne Besatzung"],
  ["STAB", "Staffelläufer übergeben ihn"],
  ["STALL", "Zuhause von Kuh und Pferd"],
  ["STEG", "Kleiner Bootsanleger"],
  ["STIL", "Art und Weise"],
  ["STURM", "Im Wasserglas oft"],
  ["SUMPF", "Moor"],
  ["TAFEL", "Kreidefläche – oder Schokostück"],
  ["TALER", "Alte Münze"],
  ["TAUBE", "Friedenssymbol – oder Ratte der Lüfte"],
  ["THEKE", "Tresen in der Kneipe"],
  ["TIARA", "Diadem der Prinzessin"],
  ["TIGER", "Gestreifte Raubkatze"],
  ["TITAN", "Leichtes Metall – oder Riese"],
  ["TOGA", "Römisches Gewand"],
  ["TOMBOLA", "Verlosung auf dem Fest"],
  ["TONIC", "Bitterlimonade zum Gin"],
  ["TORERO", "Stierkämpfer"],
  ["TRESOR", "Panzerschrank"],
  ["TRUHE", "Kiste mit Deckel"],
  ["TUNNEL", "Licht am Ende des …"],
  ["TUSCH", "Trommelwirbel nach der Pointe"],
  ["URNE", "Wahlbox"],
  ["VENTIL", "Damit pumpt man den Reifen auf"],
  ["VERS", "Zeile im Gedicht"],
  ["VIDEO", "Clip auf YouTube"],
  ["VISIER", "Klappe am Helm"],
  ["WAAGE", "Lügt angeblich nach den Feiertagen"],
  ["WABE", "Sechseckige Bienenzelle"],
  ["WAFFE", "Mittel zum Kampf"],
  ["WAISE", "Kind ohne Eltern"],
  ["WALZER", "Wiener Dreivierteltakt"],
  ["WATT", "Einheit der Leistung – oder Schlick an der Nordsee"],
  ["WEHR", "Stauanlage im Fluss – Feuer…"],
  ["WEIHER", "Kleiner Teich"],
  ["WICHT", "Kleiner Kerl"],
  ["WIEGE", "Kinderbett zum Schaukeln"],
  ["WINDEL", "Babys erste Hose"],
  ["WIPPE", "Spielplatzbrett für zwei"],
  ["WRACK", "Gesunkenes Schiff"],
  ["ZACKE", "Spitze an der Krone"],
  ["ZANK", "Streit"],
  ["ZAPFEN", "Hängt an der Tanne"],
  ["ZECHE", "Bergwerk – oder Rechnung in der Kneipe"],
  ["ZELLE", "Kleinste Lebenseinheit – oder Knastraum"],
  ["ZIEGE", "Meckert – liefert Käse"],
  ["ZIEGEL", "Dachstein"],
  ["ZINS", "Gibt's fürs Sparen"],
  ["ZIRKUS", "Manege frei!"],
  ["ZOFE", "Kammerdienerin"],
  ["ZOPF", "Geflochtene Haare – oder Hefegebäck"],
  ["ZUNFT", "Handwerkerverband"],
  ["ZUNGE", "Liegt einem ein Wort darauf"],
  ["ZWIRN", "Starker Faden"],
  ["MATCH", "Gegenseitiges Like bei Tinder"],
  ["SWIPE", "Wischbewegung auf dem Display"],
  ["STALKEN", "Im Netz heimlich jemandem nachspüren"],
  ["SPAMMEN", "Den Chat mit Nachrichten fluten"],
  ["TRACKEN", "Schritte oder Pakete verfolgen"],
  ["UPCYCLING", "Aus Altem Neues basteln"],
  ["THRIFTEN", "Secondhand shoppen"],
  ["SHISHA", "Wasserpfeife"],
  ["EBOOK", "Buch auf dem Reader"],
  ["HOTSPOT", "Handy als WLAN-Quelle"],
  ["WIFI", "WLAN auf Englisch"],
  ["USBSTICK", "Kleiner Datenträger"],
  ["AIRTAG", "Apple-Ortungsplättchen am Koffer"],
  ["POWERNAP", "Kurzschlaf in der Mittagspause"],
  ["CHECKIN", "Abfertigung am Flughafen"],
  ["UPGRADE", "Aufwertung, z. B. in die Business Class"],
  ["LOUNGE", "Wartebereich für Vielflieger"],
  ["GADGET", "Technisches Spielzeug"],
  ["SETUP", "Schreibtisch-Ausstattung von Gamern"],
  ["GAMING", "Videospielen als Hobby"],
  ["SPEEDRUN", "Spiel so schnell wie möglich durchspielen"],
  ["SKIN", "Optisches Outfit für die Spielfigur"],
  ["LOOT", "Beute im Videospiel"],
  ["EMOTE", "Tänzchen der Spielfigur"],
  ["PATCH", "Fehlerbehebung per Update"],
  ["APOLLO", "Mondprogramm der NASA"],
  ["SPUTNIK", "Erster Satellit"],
  ["ISOTOP", "Atomvariante mit anderer Neutronenzahl"],
  ["VAKUUM", "Luftleerer Raum"],
  ["PLASMA", "Vierter Aggregatzustand – oder Blutbestandteil"],
  ["NEURON", "Nervenzelle"],
  ["SYNAPSE", "Kontaktstelle zwischen Nervenzellen"],
  ["KEIM", "Bakterie – oder Spross"],
  ["HORMON", "Botenstoff im Körper"],
  ["INSULIN", "Hormon bei Diabetes"],
  ["DOPAMIN", "Glückshormon beim Scrollen"],
  ["BAKTERIE", "Einzeller, gut oder böse"],
  ["MOLEKÜL", "Verbund von Atomen"],
  ["QUANT", "Kleinstes Energiepaket"],
  ["GENOM", "Gesamte Erbinformation"],
  ["AMEISE", "Fleißiges Krabbeltier"],
  ["WESPE", "Stört beim Pflaumenkuchen"],
  ["HUMMEL", "Pummelige Biene"],
  ["LIBELLE", "Insekt mit vier Flügeln"],
  ["ZIKADE", "Zirpt im Süden"],
  ["ZECKE", "Blutsauger im Gras"],
  ["LAUS", "Läuft einem über die Leber"],
  ["FLIEGE", "Summt – oder Querbinder am Hals"],
  ["SKORPION", "Stachel am Schwanzende"],
  ["SCHNECKE", "Trägt ihr Haus mit sich"],
  ["MUSCHEL", "Am Strand gesammelt"],
  ["KREBS", "Läuft seitwärts"],
  ["GARNELE", "Shrimp"],
  ["DELFIN", "Klügster Meeressäuger"],
  ["ROBBE", "Heuler ist ein Junges davon"],
  ["WALROSS", "Hat Stoßzähne und Schnauzbart"],
  ["MÖWE", "Klaut Pommes am Strand"],
  ["KRÄHE", "Hackt der anderen kein Auge aus"],
  ["HAMSTER", "Nagt im Laufrad"],
  ["RATTE", "Nager in der Kanalisation"],
  ["WIESEL", "Flinker kleiner Räuber"],
  ["DROMEDAR", "Kamel mit einem Höcker"],
  ["NASHORN", "Dickhäuter mit Horn"],
  ["NILPFERD", "Flusspferd"],
  ["GORILLA", "Größter Menschenaffe"],
  ["SCHIMPANSE", "Nächster Verwandter des Menschen"],
  ["ORANGUTAN", "Roter Menschenaffe"],
  ["FAULTIER", "Hängt kopfüber, bewegt sich kaum"],
  ["ESELSOHR", "Knick im Buch"],
  ["ZIMTSTERN", "Weihnachtsplätzchen"],
  ["LEBKUCHEN", "Nürnberger Spezialität"],
  ["STOLLEN", "Dresdner Weihnachtsgebäck – oder Bergwerksgang"],
  ["GLÜHWEIN", "Heißes vom Weihnachtsmarkt"],
  ["PUNSCH", "Heißgetränk mit Rum"],
  ["ADVENT", "Zeit mit vier Kerzen"],
  ["NIKOLAUS", "Füllt am 6. Dezember die Stiefel"],
  ["KRAMPUS", "Böser Begleiter des Nikolaus"],
  ["RENTIER", "Zieht den Schlitten"],
  ["BESCHERUNG", "Moment der Geschenke"],
  ["FASCHING", "Karneval im Süden"],
  ["KONFETTI", "Bunte Papierschnipsel"],
  ["KOSTÜM", "Verkleidung"],
  ["MASKOTTCHEN", "Glücksbringer-Figur"],
  ["HALLOWEEN", "Fest mit Kürbissen"],
  ["KÜRBIS", "Wird geschnitzt – oder Suppe"],
  ["OKTOBERFEST", "Wiesn in München"],
  ["MASS", "Bayerisches Bierglas"],
  ["DIRNDL", "Trachtenkleid"],
  ["LEDERHOSE", "Bayerische Tracht für Männer"],
  ["WEISSWURST", "Darf das Mittagsläuten nicht hören"],
  ["OBATZDA", "Bayerischer Käseaufstrich"],
  ["LABSKAUS", "Seemannsgericht aus Hamburg"],
  ["MATJES", "Junger Hering"],
  ["MAULTASCHE", "Schwäbische Teigtasche"],
  ["SPÄTZLE", "Schwäbische Eiernudeln"],
  ["SCHNITZEL", "Paniertes Fleisch aus Wien"],
  ["ROULADE", "Gerolltes Fleisch"],
  ["SAUERBRATEN", "Rheinischer Braten"],
  ["KNÖDEL", "Kloß"],
  ["EINTOPF", "Alles in einem Topf"],
  ["FRIKADELLE", "Bulette, Fleischpflanzerl"],
  ["BULETTE", "Berliner Frikadelle"],
  ["KASSLER", "Gepökeltes Schweinefleisch"],
  ["SCHMALZ", "Fett aufs Brot – oder Kitsch im Lied"],
  ["MEERRETTICH", "Scharfe Wurzel – in Bayern Kren"],
  ["KREN", "Österreichisch für Meerrettich"],
  ["RADIESCHEN", "Rote Knolle im Salat"],
  ["RUCOLA", "Salat auf der Pizza"],
  ["SPARGEL", "Weißes Gold im Frühling"],
  ["KOHL", "Gemüse – oder Unsinn, den man redet"],
  ["LAUCH", "Porree"],
  ["FENCHEL", "Knolle mit Anisgeschmack"],
  ["ZUCCHINI", "Grünes Kürbisgewächs"],
  ["AUBERGINE", "Lila Gemüse"],
  ["PAPRIKA", "Gemüse in Rot, Gelb, Grün"],
  ["CHILI", "Scharfe Schote"],
  ["MANGO", "Exotische Frucht"],
  ["PAPAYA", "Tropische Frucht"],
  ["ANANAS", "Gehört auf Pizza? Streitfrage"],
  ["LITSCHI", "Weiße Frucht mit rauer Schale"],
  ["DATTEL", "Süße Frucht der Palme"],
  ["FEIGE", "Frucht mit vielen Kernen"],
  ["PFLAUME", "Wird zum Kuchen – oder schlaffer Mensch"],
  ["APRIKOSE", "Marille"],
  ["MARILLE", "Österreichisch für Aprikose"],
  ["PFIRSICH", "Pelzige Frucht"],
  ["HOLUNDER", "Blüten für Sirup und Hugo"],
  ["HEIDELBEERE", "Blaue Waldbeere"],
  ["HIMBEERE", "Rote Beere"],
  ["JOHANNISBEERE", "Rote oder schwarze Beere am Strauch"],
  ["MELONE", "Saftige Sommerfrucht – oder runder Hut"],
  ["KOKOS", "Nuss von der Palme"],
  ["MANDEL", "Steinfrucht – oder Organ im Hals"],
  ["PISTAZIE", "Grüne Nuss, Dubai-Schoko-Hype"],
  ["ERDNUSS", "Snack aus der Dose"],
  ["CASHEW", "Gebogener Nusskern"],
  ["ROSINE", "Getrocknete Traube"],
  ["ESSIG", "Sauer, zum Salat"],
  ["BALSAMICO", "Dunkler Essig aus Modena"],
  ["MAYO", "Kurz für Mayonnaise"],
  ["AIOLI", "Knoblauchmayonnaise"],
  ["SALSA", "Scharfe Soße – oder Tanz"],
  ["DIP", "Soße zum Eintunken"],
  ["TOPPING", "Belag obendrauf"],
  ["STREUSEL", "Krümel auf dem Kuchen"],
  ["GLASUR", "Überzug auf dem Donut"],
  ["KARAMELL", "Gebrannter Zucker"],
  ["KAKAO", "Heiße Schoki"],
  ["MILCHSHAKE", "Gemixtes Milchgetränk"],
  ["SODA", "Sprudelwasser"],
  ["SCHORLE", "Saft mit Sprudel"],
  ["RADLER", "Bier mit Limo"],
  ["ALSTER", "Hamburger Radler – oder See"],
  ["KÖLSCH", "Bier aus Köln in kleinen Stangen"],
  ["ALTBIER", "Düsseldorfer Bier"],
  ["WEIZEN", "Bier – oder Getreide"],
  ["BOWLE", "Fruchtiges Partygetränk"],
  ["LIKÖR", "Süßer Schnaps"],
  ["WHISKY", "Schottischer Schnaps"],
  ["COGNAC", "Französischer Weinbrand"],
  ["GROG", "Heißer Rum mit Wasser"],
  ["CHAMPAGNER", "Edler Schaumwein"],
  ["MACCHIATO", "Gefleckter Kaffee"],
  ["CHAI", "Gewürztee aus Indien"],
  ["ROOIBOS", "Rotbuschtee"],
  ["KAMILLE", "Tee bei Bauchweh"],
);
