// Stapel 3: Mischung aus Crosswordese, Klassikern und modernen Begriffen (bewusst unsortiert)
WORDS.push(
  ["ARIE", "Solonummer der Diva in der Oper"],
  ["QUARK", "Weißer Brotaufstrich – oder Elementarteilchen", "Redet man, wenn man Unsinn erzählt"],
  ["EMU", "Australischer Laufvogel"],
  ["STREAMING", "Hat die Videothek abgelöst"],
  ["ERLE", "Baum am Bachufer, Goethes Erlkönig lässt grüßen"],
  ["JODELN", "Alpenländischer Gesang mit Kehlkopfsprüngen"],
  ["ZEUS", "Göttervater mit Blitzen im Gepäck"],
  ["ORKAN", "Sturm in Stärke 12"],
  ["OBOE", "Doppelrohrblatt-Instrument, das im Orchester den Ton angibt"],
  ["NEON", "Edelgas der Leuchtreklame"],
  ["ESPE", "Baum, dessen Laub zittert"],
  ["YAK", "Zottelrind aus dem Himalaya"],
  ["ALIBI", "Hat der Verdächtige hoffentlich für die Tatzeit"],
  ["ROVER", "Fährt ferngesteuert über den Mars"],
  ["ELAN", "Schwung, Begeisterung"],
  ["KAIN", "Biblischer Brudermörder"],
  ["ELBE", "Fluss, an dem Dresden und Hamburg liegen"],
  ["VETO", "Einspruch, der alles blockiert"],
  ["GNU", "Afrikanische Antilope – und freies Softwareprojekt"],
  ["EBBE", "Wenn das Wasser weg ist, ist an der Nordsee …", "Herrscht am Monatsende auf dem Konto"],
  ["PODCASTER", "Redet wöchentlich ins Mikro"],
  ["OPUS", "Werk eines Komponisten (lat.)"],
  ["ISAR", "Fluss durch München"],
  ["XENON", "Edelgas in Autoscheinwerfern"],
  ["NOAH", "Baute eine Arche für alle Tiere"],
  ["IDOL", "Hängt als Poster im Jugendzimmer"],
  ["TAIFUN", "Wirbelsturm in Ostasien"],
  ["MOLL", "Tongeschlecht der traurigen Lieder"],
  ["LUCHS", "Wildkatze mit Pinselohren"],
  ["NERO", "Römischer Kaiser, der beim Brand Roms gegeigt haben soll"],
  ["JUX", "Spaß, Scherz"],
  ["ULME", "Laubbaum, der unter einem Pilzsterben leidet"],
  ["OASE", "Wasserstelle zwischen Dünen"],
  ["KARMA", "Kommt angeblich zurück, wenn man fies war"],
  ["ODIN", "Einäugiger Göttervater der Germanen"],
  ["TROJA", "Stadt, die ein Holzpferd zu Fall brachte"],
  ["VIOLA", "Bratsche, mit italienischem Namen"],
  ["EIBE", "Giftiger Nadelbaum in Parkhecken"],
  ["DUBAI", "Stadt mit dem höchsten Gebäude der Welt"],
  ["AMEN", "Steht am Ende des Gebets"],
  ["ZINK", "Metall in Sonnencreme und Dachrinnen"],
  ["OKAPI", "Waldgiraffe aus dem Kongo"],
  ["EDEN", "Paradiesgarten der Bibel"],
  ["VAGE", "Unbestimmt, ungenau"],
  ["ÄTNA", "Aktiver Vulkan auf Sizilien"],
  ["KOMET", "Schweifstern"],
  ["ADLER", "Wappenvogel Deutschlands"],
  ["RHEIN", "Fluss mit Loreley-Felsen"],
  ["KOBRA", "Schlange mit Schirm am Hals"],
  ["TENOR", "Hohe Männerstimme – oder Grundhaltung einer Aussage"],
  ["LAMA", "Spuckt, wenn es sich ärgert"],
  ["ALPAKA", "Flauschiges Andentier, Instagram-Liebling"],
  ["MEDUSA", "Wer sie ansah, wurde zu Stein"],
  ["ROM", "Ewige Stadt"],
  ["OSLO", "Hauptstadt mit Nobelpreis-Feier (Frieden)"],
  ["ASTER", "Herbstblume mit Sternenname"],
  ["FAUST", "Doktor, der einen Pakt mit Mephisto schloss"],
  ["ESCAPEROOM", "Rätselraum, aus dem man in 60 Minuten raus muss"],
  ["ARGON", "Edelgas, das häufigste in der Luft"],
  ["AJAX", "Griechischer Held – und Fußballklub aus Amsterdam"],
  ["KAKADU", "Papagei mit Haube"],
  ["NATO", "Militärbündnis mit Sitz in Brüssel"],
  ["WOLGA", "Längster Fluss Europas"],
  ["ZITHER", "Saiteninstrument aus „Der dritte Mann“"],
  ["BARISTA", "Zaubert Latte Art"],
  ["HERA", "Eifersüchtige Gattin des Zeus"],
  ["FJORD", "Tief eingeschnittene Meeresbucht in Norwegen"],
  ["AAR", "Dichterisches Wort für Adler"],
  ["LEGUAN", "Echse, die als Haustier im Terrarium lebt"],
  ["MOZART", "Wolfgang Amadeus aus Salzburg"],
  ["KANON", "Lied, bei dem alle zeitversetzt einsetzen"],
  ["IBIS", "Heiliger Vogel der Ägypter"],
  ["EFEU", "Kletterpflanze an der Hauswand"],
  ["JOVIAL", "Gönnerhaft freundlich"],
  ["ORCA", "Schwertwal"],
  ["URAN", "Brennstoff im Atomkraftwerk"],
  ["MARS", "Roter Planet – oder Schokoriegel"],
  ["ELLE", "Unterarmknochen – und altes Längenmaß"],
  ["SPREE", "Fluss durch Berlin"],
  ["KAIRO", "Hauptstadt mit Pyramiden vor der Tür"],
  ["TUBA", "Tiefstes Blechblasinstrument"],
  ["OMAN", "Sultanat am Arabischen Meer"],
  ["ODER", "Grenzfluss zu Polen – auch ein Bindewort"],
  ["KITSCH", "Gartenzwerg mit Glitzer"],
  ["XYLOFON", "Schlaginstrument mit Holzplatten"],
  ["LINDE", "Baum, unter dem man früher Gericht hielt"],
  ["SALOMO", "Biblischer König, berühmt für seine Weisheit"],
  ["HELIUM", "Macht die Stimme quietschig"],
  ["RIGA", "Hauptstadt Lettlands"],
  ["MATCHA", "Grüner Teepulver-Trend"],
  ["KRAKE", "Hat acht Arme und drei Herzen"],
  ["ATLAS", "Kartenbuch – oder Titan, der den Himmel stemmt"],
  ["ZENIT", "Höhepunkt – Punkt genau über dem Kopf"],
  ["MAU", "So läuft das Geschäft, wenn es schlecht läuft"],
  ["PEDANT", "Erbsenzähler"],
  ["ELIXIER", "Zaubertrank"],
  ["ARCHE", "Rettungsschiff der Bibel"],
  ["DACHS", "Grimbart in der Fabel"],
  ["FLAIR", "Gewisses Etwas, Ausstrahlung"],
  ["KIEL", "Landeshauptstadt an der Förde"],
  ["SATURN", "Planet mit Ringen"],
  ["VULKAN", "Spuckt Lava"],
  ["DUETT", "Gesang zu zweit"],
  ["ZYNISCH", "Bissig spöttisch"],
  ["OTTER", "Spielt im Fluss mit Steinen"],
  ["ISS", "Raumstation im Erdorbit (Abk.)"],
  ["FAGOTT", "Tiefes Holzblasinstrument"],
  ["GOETHE", "Dichter des „Faust“"],
  ["TOFU", "Sojaquark"],
  ["ROCHEN", "Flacher Fisch mit Flügeln"],
  ["AXEL", "Sprung beim Eiskunstlauf"],
  ["SYLT", "Insel mit Promis und Fischbrötchen"],
  ["AGAVE", "Pflanze für Tequila"],
  ["ZWINKERN", "Mit einem Auge Signale senden"],
  ["ESCHE", "Weltenbaum Yggdrasil war eine"],
  ["GALAXIE", "Milchstraße ist eine"],
  ["JUDAS", "Verriet für 30 Silberlinge"],
  ["ANDEN", "Gebirge Südamerikas"],
  ["KRESSE", "Wächst auf feuchter Watte"],
  ["NIVEAU", "Sinkt bei Reality-TV angeblich"],
  ["ALGE", "Grünzeug im Teich"],
  ["PIZZERIA", "Hier wird mit Holzofen gebacken"],
  ["VISUM", "Einreiseerlaubnis im Pass"],
  ["UNKE", "Pessimistische Kröte – sieht immer schwarz"],
  ["BACH", "Kleiner Fluss – oder Thomaskantor"],
  ["RÜGEN", "Insel mit Kreidefelsen"],
  ["QUALLE", "Glibbriges Meerestier mit Nesseln"],
  ["DUR", "Tongeschlecht der fröhlichen Lieder"],
  ["IGEL", "Rollt sich bei Gefahr zusammen"],
  ["IRAN", "Staat mit Hauptstadt Teheran"],
  ["EXAKT", "Haargenau"],
  ["KONDITOR", "Macht Torten beruflich"],
  ["HARFE", "Instrument der Engel"],
  ["APOLL", "Gott des Lichts und der Musen"],
  ["LIMA", "Hauptstadt Perus"],
  ["SENSE", "Werkzeug des Sensenmanns"],
  ["NIERE", "Organ, das man doppelt hat"],
  ["CELLO", "Wird zwischen den Knien gespielt"],
  ["GECKO", "Echse, die an der Decke laufen kann"],
  ["ADAM", "Erster Mensch der Bibel"],
  ["EVA", "Biss in den verbotenen Apfel"],
  ["KAJAK", "Paddelboot, das vorwärts wie rückwärts gleich heißt"],
  ["UFO", "Fliegende Untertasse"],
  ["CHROM", "Glänzt an Oldtimern"],
  ["EBRO", "Spanischer Fluss, Kreuzworträtsel-Dauergast"],
  ["SEINE", "Fluss durch Paris"],
  ["PANDA", "Bambusfresser, WWF-Logo"],
  ["TIRAMISU", "Dessert mit Mascarpone und Espresso"],
  ["DOHA", "Hauptstadt Katars"],
  ["TEXTEN", "Werbesprüche schreiben – oder Nachrichten tippen"],
  ["MONET", "Maler der Seerosen"],
  ["ROMEO", "Julias Liebster"],
  ["OPAL", "Schillernder Schmuckstein"],
  ["JADE", "Grüner Schmuckstein aus China"],
  ["ONYX", "Schwarzer Schmuckstein"],
  ["RUBIN", "Roter Edelstein"],
  ["SAPHIR", "Blauer Edelstein"],
  ["TOPAS", "Gelblicher Edelstein"],
  ["BERN", "Bundesstadt der Schweiz"],
  ["ULM", "Stadt mit dem höchsten Kirchturm der Welt"],
  ["PEGEL", "Wasserstand am Fluss – oder Alkoholspiegel"],
  ["NEKTAR", "Göttertrank – oder Blütensaft"],
  ["ZEBRA", "Streifen auf der Straße – oder in der Savanne"],
  ["EULE", "Nach Athen tragen ist überflüssig"],
  ["HOBEL", "Werkzeug, bei dem Späne fliegen"],
  ["KORK", "Steckt im Weinflaschenhals"],
  ["JUTE", "Faser für Einkaufsbeutel"],
  ["TOGO", "Westafrikanischer Staat – oder Coffee to …"],
  ["MALI", "Staat mit Timbuktu"],
  ["LAOS", "Binnenstaat am Mekong"],
  ["KUBA", "Insel der Zigarren und Oldtimer"],
  ["PERU", "Land von Machu Picchu"],
  ["CHILE", "Langes, schmales Land in Südamerika"],
  ["NEPAL", "Staat mit dem Mount Everest"],
  ["KENIA", "Safariland mit Hauptstadt Nairobi"],
  ["JEMEN", "Staat am Golf von Aden"],
  ["FIDSCHI", "Inselstaat im Südpazifik"],
  ["TONGA", "Inselkönigreich im Pazifik"],
  ["SAMOA", "Inselstaat in Polynesien"],
  ["SEOUL", "Hauptstadt von K-Pop"],
  ["TOKIO", "Größte Metropole der Welt"],
  ["LUZERN", "Schweizer Stadt mit Kapellbrücke"],
  ["GRAZ", "Zweitgrößte Stadt Österreichs"],
  ["LINZ", "Österreichische Stadt mit der berühmten Torte"],
  ["PRAG", "Goldene Stadt an der Moldau"],
  ["ATHEN", "Hauptstadt mit Akropolis"],
  ["MALTA", "Kleinster EU-Staat"],
  ["KRETA", "Größte griechische Insel"],
  ["IBIZA", "Partyinsel der Balearen"],
  ["ELBA", "Napoleons erste Verbannungsinsel"],
  ["KORFU", "Ionische Insel mit Sisi-Palast"],
  ["BALI", "Insel der Götter, Digital-Nomaden-Hotspot"],
  ["EIGER", "Berg mit berüchtigter Nordwand"],
  ["ARARAT", "Hier soll die Arche gestrandet sein"],
  ["FUJI", "Heiliger Berg Japans"],
  ["BROCKEN", "Höchster Berg im Harz, Hexentanzplatz"],
  ["DONAU", "Fluss, der durch vier Hauptstädte fließt"],
  ["MOSEL", "Weinfluss mit vielen Schleifen"],
  ["WESER", "Fluss durch Bremen"],
  ["MAIN", "Fluss mit Frankfurter Skyline"],
  ["INN", "Fluss, der Innsbruck seinen Namen gab"],
  ["RUHR", "Fluss, der einem Pott den Namen gibt"],
  ["SAAR", "Fluss mit großer Schleife"],
  ["EMS", "Fluss durch Ostfriesland"],
  ["HAVEL", "Fluss durch Potsdam"],
  ["TIBER", "Fluss durch Rom"],
  ["THEMSE", "Fluss durch London"],
  ["TIGRIS", "Fluss Mesopotamiens, Partner des Euphrat"],
  ["LOIRE", "Fluss der Schlösser in Frankreich"],
  ["ALPEN", "Höchstes Gebirge Europas"],
  ["HARZ", "Baumsaft – oder Mittelgebirge"],
  ["EIFEL", "Mittelgebirge mit Maaren und Nürburgring"],
  ["FEILE", "Werkzeug für Nägel und Metall"],
  ["AHLE", "Stechwerkzeug des Schusters"],
  ["ZANGE", "Werkzeug zum Kneifen"],
  ["MEISSEL", "Werkzeug des Bildhauers"],
  ["SPATEN", "Gartenwerkzeug zum Umgraben"],
  ["KELLE", "Suppen… oder Maurerwerkzeug"],
  ["SICHEL", "Mondform – oder Erntemesser"],
  ["LEBER", "Organ, das unter Alkohol leidet"],
  ["LUNGE", "Atmungsorgan"],
  ["MILZ", "Organ links im Oberbauch"],
  ["GALLE", "Kommt einem bei Ärger hoch"],
  ["RIPPE", "Gibt's als Spare… vom Grill"],
  ["WADE", "Bekommt beim Sport Krämpfe"],
  ["FERSE", "Achilles hatte hier seine Schwachstelle"],
  ["NABEL", "Mittelpunkt – der Welt oder des Bauches"],
  ["STIRN", "Wird gerunzelt"],
  ["PUPILLE", "Schwarzer Punkt im Auge"],
  ["IRIS", "Regenbogenhaut im Auge"],
  ["SEIDE", "Gespinst der Raupe"],
  ["WOLLE", "Gestrickt im Winterpulli"],
  ["LEINEN", "Stoff für Sommerhemden"],
  ["MARMOR", "Stein für Statuen"],
  ["GRANIT", "Auf … beißen: keinen Erfolg haben"],
  ["BETON", "Baustoff für Brutalismus"],
  ["NYLON", "Kunstfaser für Strümpfe"],
  ["TWEED", "Karierter Wollstoff der Briten"],
  ["TEER", "Schwarzer Straßenbelag"],
  ["MOHN", "Rote Blume, Samen auf dem Brötchen"],
  ["TULPE", "Holländische Blume"],
  ["NELKE", "Blume am Revers – oder Gewürz"],
  ["LILIE", "Wappenblume der französischen Könige"],
  ["ORCHIDEE", "Exotische Blume auf der Fensterbank"],
  ["LAVENDEL", "Lila Duftpflanze aus der Provence"],
  ["SALBEI", "Kraut für Halsschmerztee"],
  ["THYMIAN", "Kraut der Provence"],
  ["DILL", "Kraut auf Gurkensalat"],
  ["MINZE", "Kraut im Mojito"],
  ["INGWER", "Scharfe Wurzel für Shots"],
  ["ZIMT", "Gewürz in Schnecken und Glühwein"],
  ["ANIS", "Gewürz mit Lakritzgeschmack"],
  ["VANILLE", "Schote für Eis und Pudding"],
  ["OREGANO", "Pizzagewürz"],
  ["KAKTUS", "Stachelige Zimmerpflanze"],
  ["ALOE", "Pflanze mit Gel gegen Sonnenbrand"],
  ["FARN", "Urzeitpflanze im Wald"],
  ["MOOS", "Grünes Polster – oder Geld, umgangssprachlich"],
  ["MISTEL", "Unter ihr wird geküsst"],
  ["AHORN", "Baum auf Kanadas Flagge"],
  ["BIRKE", "Baum mit weißer Rinde"],
  ["TANNE", "Weihnachtsbaum-Klassiker"],
  ["EICHE", "Kräftiger Baum, auf deutschen Cent-Münzen"],
  ["BUCHE", "Holz-Klassiker im Wald"],
  ["PAPPEL", "Hoher Baum, dessen Samen im Mai wie Schnee fliegen"],
  ["WEIDE", "Grasland – oder Baum am Bach"],
  ["HASEL", "Strauch für Nüsse"],
  ["SPATZ", "Frecher Vogel – oder Kosewort"],
  ["AMSEL", "Schwarzer Singvogel"],
  ["ELSTER", "Diebischer Vogel"],
  ["MEISE", "Hat eine, wer spinnt"],
  ["STORCH", "Bringt angeblich Babys"],
  ["REIHER", "Grauer Vogel am Teich"],
  ["KRANICH", "Vogel im Lufthansa-Logo"],
  ["SCHWAN", "Weißer Vogel, der Ballett inspirierte"],
  ["FALKE", "Schnellster Vogel im Sturzflug"],
  ["KAUZ", "Komischer … – oder kleine Eule"],
  ["PFAU", "Schlägt ein Rad"],
  ["TUKAN", "Vogel mit Riesenschnabel"],
  ["KOLIBRI", "Winziger Vogel, der rückwärts fliegen kann"],
  ["STRAUSS", "Größter Vogel – oder Blumengebinde"],
  ["KIWI", "Vogel – und Frucht – aus Neuseeland"],
  ["ARA", "Bunter Papagei"],
  ["JAGUAR", "Raubkatze – und britische Automarke"],
  ["GEPARD", "Schnellstes Landtier"],
  ["PANTHER", "Schwarze Raubkatze"],
  ["KAMEL", "Hat zwei Höcker"],
  ["GAZELLE", "Flinke Antilope"],
  ["KOALA", "Schläft 20 Stunden am Tag"],
  ["LEMUR", "Halbaffe aus Madagaskar"],
  ["MARDER", "Beißt Kabel im Auto durch"],
  ["BIBER", "Baut Dämme"],
  ["HECHT", "Raubfisch – oder Kopfsprung"],
  ["LACHS", "Rosa Fisch für Sushi"],
  ["FORELLE", "Fisch, über den Schubert komponierte"],
  ["KARPFEN", "Weihnachtsfisch in manchen Familien"],
  ["ZANDER", "Edler Raubfisch"],
  ["MOLCH", "Amphibie im Gartenteich"],
  ["KROETE", "Warzige Amphibie – oder Geld, salopp"],
  ["ECHSE", "Reptil mit Schwanz"],
  ["VIPER", "Giftschlange"],
  ["HUMMER", "Teures Krustentier"],
  ["AUSTER", "Muschel mit Perle"],
  ["SEPIA", "Tintenfisch – oder bräunlicher Fotofilter"],
  ["HERMELIN", "Wiesel im weißen Winterfell"],
  ["ILTIS", "Stinkender Marder"],
  ["DROSSEL", "Singvogel – oder Bremse für den Datenverkehr"],
  ["ASTRONAUT", "Fliegt ins All"],
  ["ORBIT", "Umlaufbahn"],
  ["JUPITER", "Größter Planet"],
  ["VENUS", "Morgenstern"],
  ["PLUTO", "Seit 2006 kein Planet mehr"],
  ["NASA", "US-Raumfahrtbehörde"],
  ["ESA", "Europäische Raumfahrtagentur (Abk.)"],
  ["CERN", "Teilchenbeschleuniger bei Genf (Abk.)"],
  ["ATOM", "Kleinster Baustein eines Elements"],
  ["LASER", "Gebündelter Lichtstrahl"],
  ["ENZYM", "Biokatalysator in Waschmitteln"],
  ["PROTEIN", "Eiweiß im Shake"],
  ["KLON", "Genetische Kopie – wie Schaf Dolly"],
  ["QUASAR", "Extrem heller Galaxienkern"],
  ["URKNALL", "Anfang von allem"],
  ["NEBEL", "Kosmische Gaswolke – oder trübe Suppe am Morgen"],
  ["OZON", "Schicht, die vor UV schützt"],
  ["RADON", "Radioaktives Gas aus dem Keller"],
  ["LITHIUM", "Leichtmetall im Akku"],
  ["KOBALT", "Blaues Metall im Akku"],
  ["NICKEL", "Metall, das Allergien auslöst"],
  ["ZINN", "Metall für Soldatenfiguren"],
  ["SILIZIUM", "Material im Valley-Namen"],
  ["QUECKSILBER", "Flüssiges Metall im alten Thermometer"],
  ["ARSEN", "Klassisches Gift im Krimi"],
  ["BOR", "Chemisches Element mit drei Buchstaben"],
  ["JOD", "Element in Salz und Tinktur"],
  ["NATRIUM", "Steckt im Kochsalz"],
  ["CHLOR", "Riecht im Schwimmbad"],
  ["KALZIUM", "Steckt in Milch und Knochen"],
  ["DARWIN", "Vater der Evolutionstheorie"],
  ["EINSTEIN", "Relativ berühmter Physiker"],
  ["CURIE", "Doppelte Nobelpreisträgerin Marie"],
  ["EDISON", "Erfinder der praktischen Glühbirne"],
  ["GALILEI", "„Und sie bewegt sich doch“"],
  ["KOLUMBUS", "Suchte Indien und fand Amerika"],
  ["CAESAR", "„Veni, vidi, vici“"],
  ["KLEOPATRA", "Ägyptische Königin mit Schlangenbiss"],
  ["CICERO", "Römischer Redner"],
  ["ATTILA", "Hunnenkönig"],
  ["HANNIBAL", "Ging mit Elefanten über die Alpen"],
  ["SOKRATES", "„Ich weiß, dass ich nichts weiß“"],
  ["PLATON", "Philosoph mit dem Höhlengleichnis"],
  ["NAPOLEON", "Kleiner Kaiser mit Hand in der Weste"],
  ["LUTHER", "Hämmerte Thesen an eine Kirchentür"],
  ["BISMARCK", "Eiserner Kanzler – oder Hering"],
  ["SCHILLER", "Dichter der „Ode an die Freude“"],
  ["KAFKA", "Autor der „Verwandlung“"],
  ["BRECHT", "Dramatiker der „Dreigroschenoper“"],
  ["BEETHOVEN", "Komponierte taub die Neunte"],
  ["WAGNER", "Komponist des „Rings“"],
  ["DALI", "Maler der zerfließenden Uhren"],
  ["PICASSO", "Maler von „Guernica“"],
  ["BANKSY", "Anonymer Streetart-Künstler"],
  ["DÜRER", "Maler des Hasen"],
  ["OBAMA", "„Yes we can“"],
  ["MERKEL", "„Wir schaffen das“"],
  ["MERZ", "Kanzler seit 2025"],
  ["HAMLET", "„Sein oder nicht sein“"],
  ["OTHELLO", "Eifersüchtiger Mohr von Venedig – oder Brettspiel"],
  ["MACBETH", "Schottischer König bei Shakespeare"],
  ["HEIDI", "Mädchen aus den Bergen bei ihrem Großvater"],
  ["MOMO", "Mädchen gegen die grauen Herren"],
  ["EMIL", "… und die Detektive"],
  ["ROBINSON", "Gestrandet mit Freitag"],
  ["GULLIVER", "Reiste zu den Liliputanern"],
  ["MOSE", "Teilte das Rote Meer"],
  ["DAVID", "Besiegte Goliath mit der Schleuder"],
  ["GOLIATH", "Riese, der gegen David verlor"],
  ["JONAS", "Saß im Bauch eines Wals"],
  ["ABEL", "Erschlagener Bruder"],
  ["MANNA", "Himmelsbrot in der Wüste"],
  ["ZION", "Berg in Jerusalem"],
  ["HALLELUJA", "Lobt den Herrn"],
  ["ISIS", "Ägyptische Göttin der Mutterschaft"],
  ["OSIRIS", "Ägyptischer Totengott"],
  ["ANUBIS", "Ägyptischer Gott mit Schakalkopf"],
  ["HADES", "Griechische Unterwelt"],
  ["STYX", "Fluss in der Unterwelt"],
  ["OLYMP", "Wohnsitz der griechischen Götter"],
  ["ITHAKA", "Heimat des Odysseus"],
  ["ARES", "Griechischer Kriegsgott"],
  ["EROS", "Griechischer Liebesgott"],
  ["ATHENE", "Göttin der Weisheit mit Eule"],
  ["ACHILL", "Held mit verwundbarer Ferse"],
  ["HELENA", "Schönste Frau, Anlass für den Trojanischen Krieg"],
  ["ODYSSEUS", "Irrte zehn Jahre heimwärts"],
  ["WALHALLA", "Halle der gefallenen Krieger"],
  ["FREYA", "Nordische Göttin der Liebe"],
  ["TROLL", "Lebt unter der Brücke"],
  ["ELFE", "Zartes Naturwesen"],
  ["GNOM", "Kleiner Erdgeist"],
  ["GOLEM", "Lehmfigur aus der Prager Sage"],
  ["UEFA", "Europäischer Fußballverband"],
  ["UNESCO", "Vergibt den Welterbe-Titel"],
  ["UNICEF", "Kinderhilfswerk der UNO"],
  ["ZDF", "Mainzer Fernsehsender (Abk.)"],
  ["ARD", "Das Erste (Abk.)"],
  ["ORF", "Österreichischer Rundfunk (Abk.)"],
  ["DDR", "Ostdeutscher Staat bis 1990 (Abk.)"],
  ["BRD", "Westdeutschland bis 1990 (Abk.)"],
  ["UDSSR", "Sowjetunion (Abk.)"],
  ["GMBH", "Firmenform mit beschränkter Haftung (Abk.)"],
  ["KFZ", "Fahrzeug mit Motor (Abk.)"],
  ["AKW", "Atomkraftwerk (Abk.)"],
  ["DFB", "Deutscher Fußball-Bund (Abk.)"],
  ["BVB", "Schwarz-gelber Klub aus Dortmund (Abk.)"],
  ["ABC", "Alphabet, kurz"],
  ["USA", "Land von Uncle Sam (Abk.)"],
  ["ADIEU", "Französischer Abschied"],
  ["CIAO", "Tschüss auf Italienisch"],
  ["AMIGO", "Freund auf Spanisch"],
  ["AGENDA", "Tagesordnung"],
  ["BONUS", "Extra-Zahlung"],
  ["CHIC", "Elegant"],
  ["DEJAVU", "Gefühl, das schon mal erlebt zu haben"],
  ["ETUI", "Brillenbehälter"],
  ["FAIBLE", "Vorliebe"],
  ["FIASKO", "Totaler Reinfall"],
  ["GUSTO", "Appetit, Lust auf etwas"],
  ["IDYLLE", "Ländliche Harmonie"],
  ["KLISCHEE", "Abgedroschenes Vorurteil"],
  ["LOBBY", "Hotelhalle – oder Interessengruppe"],
  ["MOTTO", "Wahlspruch einer Party"],
  ["PARFUM", "Duft aus dem Flakon"],
  ["SAFARI", "Tiersafari im Jeep – oder Apples Browser"],
  ["TABU", "Darüber spricht man nicht – oder Ratespiel"],
  ["TORSO", "Rumpf einer Statue"],
  ["KANTOR", "Leitet den Kirchenchor"],
  ["IMKER", "Hält Bienen"],
  ["HIRTE", "Hütet Schafe"],
  ["FÖRSTER", "Kümmert sich um den Wald"],
  ["METZGER", "Fleischer im Süden"],
  ["OPTIKER", "Verkauft Brillen"],
  ["NOTAR", "Beglaubigt den Kaufvertrag"],
  ["ANWALT", "Vertritt vor Gericht"],
  ["MAURER", "Baut Wände Stein auf Stein"],
  ["TISCHLER", "Schreiner im Norden"],
  ["FRISEUR", "Schneidet Haare"],
  ["PFLEGER", "Kümmert sich im Krankenhaus"],
  ["DESIGNER", "Gestaltet Mode oder Apps"],
  ["COACH", "Trainer – auch fürs Leben"],
  ["INFLUENCERIN", "Verdient mit Rabattcodes"],
  ["DATINGAPP", "Hier wird nach links und rechts gewischt"],
  ["FOODTRUCK", "Imbiss auf Rädern"],
  ["POPUP", "Laden auf Zeit – oder nerviges Fenster"],
  ["JUBELN", "Beim Tor laut feiern"],
  ["JAMMERN", "Klagen auf hohem Niveau"],
  ["QUAKEN", "Frosch macht das"],
  ["QUATSCHEN", "Plaudern"],
  ["QUENGELN", "Kind an der Supermarktkasse"],
  ["QUIETSCHEN", "Machen Reifen und Gummienten"],
  ["QUALMEN", "Wie ein Schlot rauchen"],
  ["MIXEN", "Cocktails oder Musik zusammenmischen"],
  ["BOXEN", "Kampfsport im Ring"],
  ["HEXEN", "Zaubern wie Bibi"],
  ["KRAXELN", "Bayerisch für klettern"],
  ["VOTEN", "Abstimmen im Netz"],
  ["ZAUBERN", "Hokuspokus machen"],
  ["ZETERN", "Lautstark klagen"],
  ["KITZELN", "Zum Lachen bringen, ohne Witz"],
  ["JONGLIEREN", "Bälle in der Luft halten"],
  ["ZACKIG", "Schnell und schneidig"],
  ["VIRTUELL", "Nur im Computer existent"],
  ["VITAL", "Voller Lebenskraft"],
  ["NAIV", "Gutgläubig"],
  ["NOBEL", "Edel – oder Preis-Stifter"],
  ["EXTREM", "Bis zum Äußersten"],
  ["LAX", "Locker, nachlässig"],
  ["FIX", "Schnell – oder: … und fertig"],
  ["PFIFFIG", "Schlau und einfallsreich"],
  ["QUIRLIG", "Lebhaft, quicklebendig"],
  ["QUER", "Diagonal – oder gegen den Strich"],
  ["SKURRIL", "Seltsam, kauzig"],
  ["MUFFIG", "Riecht wie ein alter Keller"],
  ["KESS", "Frech, aber charmant"],
  ["KECK", "Vorwitzig"],
  ["RAR", "Selten"],
  ["ROSIG", "Wie die Zukunft im Optimismus"],
  ["ÖDE", "Langweilig"],
  ["PRALL", "Bis zum Platzen gefüllt"],
  ["SCHRILL", "Grell, laut"],
  ["AHN", "Vorfahr"],
  ["OHEIM", "Altes Wort für Onkel"],
  ["ELEN", "Anderes Wort für Elch"],
  ["ESSE", "Schmiedekamin"],
  ["STER", "Raummaß für Brennholz"],
  ["HAG", "Hecke, Gehege – altertümlich"],
  ["AUE", "Flusswiese"],
  ["EGEL", "Blutsauger im Teich"],
  ["AAS", "Futter für Geier"],
  ["TRAN", "Fischöl – im … sein: verschlafen"],
  ["TANG", "Seetang am Strand"],
  ["RIED", "Schilfgebiet"],
  ["ODEM", "Poetisch für Atem"],
  ["LEU", "Poetisch für Löwe"],
  ["MAHD", "Das Mähen der Wiese"],
  ["OBI", "Japanischer Gürtel – oder Baumarkt"],
  ["SUMO", "Japanisches Ringen der Schwergewichte"],
  ["SAKE", "Japanischer Reiswein"],
  ["TEMPEL", "Heiligtum"],
  ["PAGODE", "Turmtempel in Asien"],
  ["SAUNA", "Finnisches Schwitzbad"],
  ["DOJO", "Trainingsraum für Kampfsport"],
  ["YOGI", "Praktiziert Yoga"],
  ["GURU", "Spiritueller Lehrer – oder Experte"],
  ["MANTRA", "Ständig wiederholte Formel"],
  ["ZEN", "Japanische Gelassenheit"],
  ["VEGANER", "Isst nichts vom Tier"],
  ["FLEXITARIER", "Isst manchmal Fleisch"],
  ["HAFERDRINK", "Milchersatz aus Getreide"],
  ["DINKEL", "Urgetreide für Brötchen"],
  ["ROGGEN", "Getreide für dunkles Brot"],
  ["GERSTE", "Getreide fürs Bier"],
  ["HAFER", "Sticht einen, wenn man übermütig ist"],
  ["HIRSE", "Getreide im Vogelfutter"],
  ["KAVIAR", "Fischeier als Luxus"],
  ["TRÜFFEL", "Edelpilz, den Schweine finden"],
  ["SHAKE", "Milch-… oder Protein-…"],
  ["PROSECCO", "Italienischer Schaumwein"],
  ["WODKA", "Russischer Schnaps"],
  ["OUZO", "Griechischer Anisschnaps"],
  ["RAKI", "Türkischer Anisschnaps"],
  ["TEQUILA", "Mexikanischer Agavenschnaps"],
  ["MOJITO", "Cocktail mit Minze und Rum"],
  ["SEKT", "Prickelt zum Anstoßen"],
  ["MET", "Honigwein der Wikinger"],
  ["CIDRE", "Französischer Apfelwein"],
  ["KEFIR", "Gesäuerte Milch"],
  ["QUICHE", "Französische Speck-Tarte"],
  ["PAELLA", "Spanisches Reisgericht"],
  ["RISOTTO", "Cremiges Reisgericht"],
  ["GULASCH", "Ungarischer Eintopf"],
  ["FONDUE", "Brot in geschmolzenen Käse tunken"],
  ["RACLETTE", "Silvester-Klassiker mit Pfännchen"],
  ["LASAGNE", "Schichtnudelauflauf, Garfields Leibspeise"],
  ["PESTO", "Basilikumsoße aus Genua"],
  ["GNOCCHI", "Kartoffelklößchen aus Italien"],
  ["KEBAB", "Gegrillte Fleischspieße"],
  ["BÖREK", "Gefüllte Teigtaschen aus der Türkei"],
  ["BAKLAVA", "Süßes Gebäck mit Pistazien"],
  ["CHURROS", "Spanisches Spritzgebäck"],
  ["PRALINE", "Edles Schokostück"],
  ["MARZIPAN", "Mandelmasse aus Lübeck"],
  ["LAKRITZ", "Schwarze Süßigkeit"],
  ["KAUGUMMI", "Klebt unterm Schultisch"],
  ["ZWIEBACK", "Doppelt gebacken, für Kranke"],
  ["BREZEL", "Verknotetes Laugengebäck"],
  ["STRUDEL", "Wiener Apfelspezialität"],
  ["KRAPFEN", "Berliner im Süden"],
  ["JUWEL", "Kostbarkeit, Edelstein"],
  ["JACHT", "Luxusboot der Superreichen"],
  ["JEEP", "Geländewagen-Klassiker"],
  ["JUNI", "Monat der Sommersonnenwende"],
  ["JULI", "Hochsommermonat"],
  ["JANUAR", "Monat der guten Vorsätze"],
  ["JURY", "Bewertet die Kandidaten"],
  ["QUOTE", "Einschaltzahl – oder Anteil"],
  ["QUERE", "Kommt einem in die …"],
  ["QUADRAT", "Vier gleiche Seiten"],
  ["QUARTETT", "Kartenspiel – oder Musikgruppe zu viert"],
  ["QUITTE", "Gelbe Frucht für Gelee"],
  ["XXL", "Übergröße (Abk.)"],
  ["EXIL", "Erzwungener Aufenthalt im Ausland"],
  ["LUXUS", "Prunk, Verschwendung"],
  ["MAXIMUM", "Höchstwert"],
  ["BOXER", "Kämpfer im Ring – oder Hunderasse"],
  ["TOXISCH", "Giftig – auch in Beziehungen"],
  ["OXID", "Rost ist eins"],
  ["SEXY", "Verführerisch"],
  ["YETI", "Schneemensch"],
  ["HOBBY", "Freizeitbeschäftigung"],
  ["POLYP", "Krake – oder Wucherung in der Nase"],
  ["SYMBOL", "Sinnbild"],
  ["TYPISCH", "Wie man es erwartet"],
  ["ZYKLUS", "Kreislauf"],
  ["ZYPRESSE", "Schlanker Baum der Toskana"],
  ["VASALL", "Lehnsmann"],
  ["VILLA", "Großes Haus mit Garten"],
  ["WIKINGER", "Seefahrer mit Drachenbooten"],
  ["VIVALDI", "Komponist der „Vier Jahreszeiten“"],
  ["VERDI", "Komponist der „Aida“ – oder Gewerkschaft"],
  ["AIDA", "Verdi-Oper – oder Kreuzfahrtschiff mit Kussmund"],
  ["TOSCA", "Puccini-Oper"],
  ["CARMEN", "Bizets Zigeunerin in der Oper"],
  ["NORMA", "Bellini-Oper – oder Durchschnitt"],
  ["SONATE", "Klavierstück in mehreren Sätzen"],
  ["FUGE", "Spalte zwischen Fliesen – oder Bach-Komposition"],
  ["TAKT", "Musikalischer Rhythmus – oder Feingefühl"],
  ["FORTE", "Laut, in der Musik"],
  ["PIANO", "Leise, in der Musik – oder Klavier"],
  ["SOPRAN", "Höchste Frauenstimme"],
  ["BANJO", "Zupfinstrument aus dem Country"],
  ["UKULELE", "Kleine Gitarre aus Hawaii"],
  ["MAESTRO", "Meister am Dirigentenpult"],
  ["ZUGABE", "Wird nach dem Konzert gefordert"],
  ["TUTTI", "Alle zusammen, im Orchester"],
);
