// Stapel 2: moderne Begriffe – Tech, Internet, Popkultur, Marken, Games
WORDS.push(
  // ---------- Tech & Internet ----------
  ["FACEBOOK", "Soziales Netzwerk, das heute vor allem Eltern nutzen", "Mark Zuckerbergs erstes großes Netzwerk"],
  ["CHATGPT", "KI-Chatbot, der 2022 einen Hype auslöste"],
  ["OPENAI", "Firma hinter ChatGPT"],
  ["MICROSOFT", "Konzern hinter Windows und Xbox"],
  ["UBUNTU", "Beliebte Linux-Distribution mit afrikanischem Namen"],
  ["DEBIAN", "Linux-Distribution, auf der Ubuntu aufbaut"],
  ["PHP", "Skriptsprache, auf der WordPress läuft"],
  ["SQL", "Abfragesprache für Datenbanken"],
  ["JAVA", "Indonesische Insel – und Programmiersprache mit Kaffeetasse im Logo"],
  ["KOTLIN", "Programmiersprache für Android-Apps, benannt nach einer russischen Insel"],
  ["RUST", "Programmiersprache mit Krebs-Maskottchen Ferris", "Englisch für Rost"],
  ["SWIFT", "Apples Programmiersprache – oder Nachname einer Popsängerin"],
  ["RUBY", "Programmiersprache, die nach einem Edelstein heißt"],
  ["PERL", "Alte Skriptsprache, klingt nach Schmuck"],
  ["BASIC", "Einsteiger-Programmiersprache der 80er-Heimcomputer"],
  ["JSON", "Datenformat mit geschweiften Klammern (Abk.)"],
  ["XML", "Auszeichnungssprache mit spitzen Klammern (Abk.)"],
  ["CSS", "Stylesheet-Sprache für Webseiten (Abk.)"],
  ["LATEX", "Textsatzsystem für Abschlussarbeiten – oder Gummimaterial"],
  ["MACOS", "Betriebssystem auf dem MacBook"],
  ["IOS", "Betriebssystem des iPhones"],
  ["GMAIL", "E-Mail-Dienst von Google"],
  ["SKYPE", "Videotelefonie-Dienst, den Microsoft 2025 abschaltete"],
  ["NOKIA", "Finnische Handymarke, bekannt für unzerstörbare Handys"],
  ["TELEGRAM", "Messenger mit Kanälen – früher auch Kurznachricht per Draht"],
  ["SIGNAL", "Verschlüsselter Messenger, den Datenschützer empfehlen"],
  ["THREEMA", "Schweizer Messenger, der Geld kostet"],
  ["SNAPCHAT", "App mit Geist-Logo und verschwindenden Bildern"],
  ["PINTEREST", "Pinnwand-Plattform für Rezepte und Deko-Ideen"],
  ["REDDIT", "Forum mit Subreddits und Upvotes"],
  ["LINKEDIN", "Karrierenetzwerk mit vielen Erfolgsgeschichten"],
  ["XING", "Deutsches Karrierenetzwerk, das gegen LinkedIn verlor"],
  ["DUOLINGO", "Sprachlern-App mit grüner Eule, die nervt"],
  ["SOUNDCLOUD", "Plattform, auf der viele Rapper ihre Karriere starteten"],
  ["VIMEO", "Videoplattform für Kreative, kleine Schwester von YouTube"],
  ["TUMBLR", "Blogplattform der 2010er-Jahre"],
  ["MYSPACE", "Soziales Netzwerk vor Facebook mit Tom als erstem Freund"],
  ["ICQ", "Messenger mit Blumen-Logo und „Uh-oh“-Ton (Abk.)"],
  ["THREADS", "Twitter-Konkurrent von Meta"],
  ["BLUESKY", "Twitter-Alternative mit Schmetterling"],
  ["MASTODON", "Dezentrale Twitter-Alternative, benannt nach einem Urzeitrüssler"],
  ["WECHAT", "Chinesische Super-App"],
  ["NVIDIA", "Grafikkartenhersteller, der durch KI-Chips reich wurde"],
  ["INTEL", "Chiphersteller mit „inside“-Werbung"],
  ["AMD", "Prozessorhersteller und Intel-Rivale (Abk.)"],
  ["LENOVO", "Chinesischer Laptophersteller, übernahm IBMs PC-Sparte"],
  ["SAMSUNG", "Koreanischer Konzern hinter den Galaxy-Handys"],
  ["HUAWEI", "Chinesischer Handyhersteller, den die USA sanktionierten"],
  ["XIAOMI", "Chinesischer Elektronikkonzern, der auch E-Autos baut"],
  ["SONY", "Japanischer Konzern hinter der PlayStation"],
  ["SIEMENS", "Deutscher Technologiekonzern aus München"],
  ["SAP", "Walldorfer Softwarekonzern (Abk.)"],
  ["ADOBE", "Firma hinter Photoshop und PDF"],
  ["PHOTOSHOP", "Bildbearbeitung, die zum Verb wurde"],
  ["ALEXA", "Sprachassistentin von Amazon"],
  ["SIRI", "Sprachassistentin auf dem iPhone"],
  ["KINDLE", "E-Reader von Amazon"],
  ["AIRPODS", "Weiße Ohrstöpsel von Apple"],
  ["WEBCAM", "Kamera am Laptop, gern abgeklebt"],
  ["HEADSET", "Kopfhörer mit Mikro fürs Homeoffice"],
  ["MONITOR", "Bildschirm am Schreibtisch"],
  ["SERVER", "Rechner, der im Netz Dienste bereitstellt"],
  ["HACKER", "Knackt Systeme – mit Hoodie im Klischee"],
  ["PHISHING", "Betrugsmails, die nach Passwörtern angeln"],
  ["VIRUS", "Schadprogramm – oder Krankheitserreger"],
  ["TROJANER", "Schadsoftware, benannt nach einem Pferd"],
  ["FIREWALL", "Digitale Brandschutzmauer"],
  ["BACKUP", "Sicherungskopie, die man immer zu spät macht"],
  ["DATEI", "Speichert man unter „final_final2“"],
  ["ORDNER", "Darin sammeln sich Dateien auf dem Desktop"],
  ["DESKTOP", "Bildschirmoberfläche voller Icons"],
  ["ICON", "Kleines Programmsymbol"],
  ["CURSOR", "Blinkender Strich beim Schreiben"],
  ["KLICK", "Geräusch der Maustaste"],
  ["LINK", "Verweis zum Anklicken"],
  ["DOMAIN", "Adresse im Netz, z. B. mit .de"],
  ["HOMEPAGE", "Startseite einer Website"],
  ["WEBSITE", "Seite im Internet"],
  ["NEWSLETTER", "Mail, die man beim Shoppen versehentlich abonniert"],
  ["ABO", "Kurz für Abonnement, z. B. beim Streamingdienst"],
  ["PREMIUM", "Bezahlversion ohne Werbung"],
  ["WERBUNG", "Läuft vor dem YouTube-Video"],
  ["ADBLOCKER", "Programm gegen Werbung im Browser"],
  ["KOMMENTAR", "Darunter wird im Netz gestritten"],
  ["SHITSTORM", "Welle der Empörung im Netz"],
  ["VIRAL", "Wie ein Video, das sich rasend verbreitet"],
  ["TRENDING", "Gerade angesagt auf der Plattform"],
  ["STORY", "Verschwindet bei Instagram nach 24 Stunden"],
  ["REEL", "Kurzvideo bei Instagram"],
  ["FEED", "Endloser Strom aus Posts"],
  ["POST", "Beitrag auf Social Media – oder gelbe Briefzustellerin"],
  ["TWEET", "Kurznachricht auf Twitter"],
  ["FILTER", "Macht im Selfie Hundeohren"],
  ["ZOOMCALL", "Videokonferenz mit „Du bist stumm geschaltet“"],
  ["MEETING", "Hätte auch eine Mail sein können"],
  ["DEADLINE", "Abgabetermin, der immer näher rückt"],
  ["STARTUP", "Junges Unternehmen mit Tischkicker"],
  ["PITCH", "Kurze Präsentation vor Investoren"],
  ["FEEDBACK", "Rückmeldung, gern konstruktiv"],
  ["WORKSHOP", "Arbeitsrunde mit Flipchart und Post-its"],
  ["COWORKING", "Geteiltes Büro für Freelancer"],
  ["FREELANCER", "Selbstständige Person ohne festen Arbeitgeber"],
  ["REMOTE", "Von überall aus arbeiten"],
  ["CHATROOM", "Virtueller Plauderraum der Neunziger"],
  ["NICKNAME", "Spitzname im Netz"],
  ["PROFIL", "Seite mit Bild und Bio auf Social Media"],
  ["ACCOUNT", "Nutzerkonto"],
  ["LOGIN", "Anmeldung mit Name und Passwort"],
  ["CHIP", "Herzstück im Computer – oder knuspriger Snack"],
  ["KABEL", "Verheddert sich in jeder Schublade"],
  ["BLUETOOTH", "Funktechnik, benannt nach einem Wikingerkönig"],
  ["GLASFASER", "Superschnelles Internetkabel"],
  ["FUNKLOCH", "Gibt es im Zug zwischen zwei Dörfern"],
  ["ROAMING", "Handynutzung im Ausland"],
  ["PREPAID", "Handyvertrag mit Guthaben"],
  ["FLATRATE", "Pauschaltarif ohne Limit"],
  ["DISPLAY", "Bildschirm des Handys"],
  ["SPEICHER", "Ist beim Handy immer voll"],
  ["GIGABYTE", "Tausend Megabyte"],
  ["KAMERA", "Hat das Handy hinten gleich dreifach"],
  ["SMARTHOME", "Zuhause, dessen Licht per App angeht"],
  ["SAUGROBOTER", "Fährt allein durch die Wohnung und verheddert sich in Socken"],
  ["DROHNE", "Fliegt mit Kamera über Festivals"],
  ["AVATAR", "Digitale Spielfigur – oder blaues Volk im Kino"],
  ["METAVERSUM", "Virtuelle Welt, an die Zuckerberg glaubte"],
  ["BLOCKCHAIN", "Technik hinter Kryptowährungen"],
  ["ETHEREUM", "Zweitgrößte Kryptowährung"],
  ["KRYPTO", "Kurz für digitale Währungen"],
  ["ONLINEBANKING", "Überweisen vom Sofa aus"],
  ["APPLEPAY", "Bezahlen per iPhone an der Kasse"],
  ["KLARNA", "Schwedischer Bezahldienst für „später zahlen“"],
  ["ZALANDO", "Onlineshop, bei dem man vor Glück schreit"],
  ["OTTO", "Versandhändler, früher bekannt für dicke Kataloge"],
  ["TEMU", "Billig-Onlineshop aus China"],
  ["SHEIN", "Ultra-Fast-Fashion-Shop aus China"],
  ["ETSY", "Onlinemarkt für Selbstgemachtes"],
  ["VINTED", "App für gebrauchte Kleidung"],
  ["KLEINANZEIGEN", "Ehemals eBay-…: Hier wird „Was ist letzte Preis?“ gefragt"],
  ["CHECK", "Doppelter blauer Haken bei WhatsApp"],
  ["STREAMER", "Spielt live vor Publikum auf Twitch"],
  ["YOUTUBER", "Verdient Geld mit Videos auf der roten Plattform"],
  ["CONTENT", "Inhalte, die Creator produzieren"],
  ["CREATOR", "Wer Inhalte fürs Netz produziert"],
  ["UNBOXING", "Videos vom Auspacken neuer Produkte"],
  ["TUTORIAL", "Anleitungsvideo"],
  ["VLOG", "Videotagebuch"],
  ["PRANK", "Streich vor laufender Kamera"],
  ["CHALLENGE", "Mutprobe, die viral geht"],
  ["SELFIESTICK", "Verlängerter Arm für Urlaubsfotos"],
  ["RINGLICHT", "Leuchtring für gutes Licht in Videos"],

  // ---------- Serien, Filme, Figuren ----------
  ["STRANGERTHINGS", "Netflix-Serie mit Eleven und dem Upside Down"],
  ["SOUTHPARK", "Zeichentrickserie mit Cartman und Kenny"],
  ["FAMILYGUY", "Zeichentrickserie mit Peter Griffin"],
  ["FUTURAMA", "Zeichentrickserie mit Roboter Bender"],
  ["THEOFFICE", "Mockumentary mit Michael Scott"],
  ["DRHOUSE", "Arztserie mit grantigem Diagnostiker (Kurztitel)"],
  ["LOST", "Serie über Flugzeugabsturz auf mysteriöser Insel"],
  ["DEXTER", "Serienmörder, der nur Mörder tötet"],
  ["SHERLOCK", "Detektiv aus der Baker Street, gespielt von Cumberbatch"],
  ["WEDNESDAY", "Netflix-Hit über Addams-Tochter mit Tanzszene"],
  ["BRIDGERTON", "Netflix-Kostümdrama mit Lady Whistledown"],
  ["THECROWN", "Netflix-Serie über die britischen Royals"],
  ["SUITS", "Anwaltsserie mit Meghan Markle"],
  ["DARK", "Deutsche Netflix-Serie über Zeitreisen in Winden"],
  ["BABYLONBERLIN", "Deutsche Serie über die 1920er-Jahre"],
  ["BIGBANGTHEORY", "Sitcom mit Sheldon Cooper (ohne „The“)"],
  ["SHELDON", "Genie mit festem Sofaplatz in einer Sitcom"],
  ["SEINFELD", "Sitcom „über nichts“"],
  ["SCRUBS", "Krankenhaus-Sitcom mit J.D. und Turk"],
  ["MONK", "Detektiv mit Zwangsstörungen"],
  ["GLEE", "Serie über einen Highschool-Chor"],
  ["SIMPSONS", "Familie aus Springfield"],
  ["BART", "Frechster Simpson"],
  ["LISA", "Kluge Saxofonistin bei den Simpsons"],
  ["MARGE", "Simpsons-Mutter mit blauem Turm auf dem Kopf"],
  ["MAGGIE", "Schnullerbaby bei den Simpsons"],
  ["SPONGEBOB", "Schwamm in der Ananas unter dem Meer"],
  ["PATRICK", "Rosa Seestern und bester Freund eines Schwamms"],
  ["PEPPAWUTZ", "Kinderserie mit rosa Ferkel"],
  ["PAWPATROL", "Kinderserie mit Rettungshunden"],
  ["BLUEY", "Australische Hundefamilie, die auch Eltern lieben"],
  ["BIENEMAJA", "Gelb-schwarze Heldin mit Freund Willi"],
  ["BIBI", "Kleine Hexe aus Neustadt (Blocksberg)"],
  ["BENJAMIN", "Elefant, der „Törööö“ macht"],
  ["SCHLUMPF", "Kleiner blauer Waldbewohner"],
  ["TELETUBBIES", "Tinky Winky, Dipsy, Laa-Laa und Po"],
  ["SESAMSTRASSE", "Hier wohnen Ernie und Bert"],
  ["ERNIE", "Berts Mitbewohner mit Quietscheentchen"],
  ["KRUEMELMONSTER", "Blaues Muppet, das Kekse verschlingt"],
  ["KERMIT", "Grüner Frosch der Muppets"],
  ["MICKYMAUS", "Disneys berühmteste Maus"],
  ["DONALD", "Ente in Matrosenkluft"],
  ["GOOFY", "Tollpatschiger Disney-Hund"],
  ["DAGOBERT", "Reichste Ente der Welt"],
  ["BAMBI", "Rehkitz aus dem Disney-Klassiker"],
  ["DUMBO", "Fliegender Disney-Elefant"],
  ["SIMBA", "Löwe aus „Der König der Löwen“"],
  ["NALA", "Simbas Freundin im Löwenrudel"],
  ["ALADDIN", "Hat einen Flaschengeist als Kumpel"],
  ["MULAN", "Kämpft als Mann verkleidet für China"],
  ["VAIANA", "Disney-Heldin, die übers Meer segelt"],
  ["ENCANTO", "Disney-Film mit „Wir reden nicht über Bruno“"],
  ["ARIELLE", "Kleine Meerjungfrau"],
  ["RAPUNZEL", "Lässt im Märchen ihr Haar herunter"],
  ["OLAF", "Schneemann, der warme Umarmungen mag"],
  ["ANNA", "Elsas Schwester aus Arendelle"],
  ["WOODY", "Cowboy-Spielzeug aus Toy Story"],
  ["BUZZ", "Spielzeug-Astronaut: Unendlichkeit und noch viel weiter"],
  ["NEMO", "Clownfisch, den man finden muss"],
  ["DORIE", "Vergesslicher Doktorfisch"],
  ["RATATOUILLE", "Pixar-Film über eine kochende Ratte"],
  ["SHREK", "Grüner Oger mit Esel"],
  ["GRU", "Bösewicht mit gelben Minions"],
  ["MADAGASCAR", "Inselstaat – und Animationsfilm mit Zoo-Tieren"],
  ["ICEAGE", "Animationsfilm mit Faultier Sid und Säbelzahntiger"],
  ["ZOOMANIA", "Disney-Film mit Häsin Judy Hopps"],
  ["PIXAR", "Animationsstudio mit springender Lampe"],
  ["MATRIX", "Film mit roter und blauer Pille"],
  ["NEO", "Auserwählter in der Matrix"],
  ["TITANIC", "Film mit DiCaprio auf sinkendem Schiff"],
  ["INCEPTION", "Film über Träume in Träumen"],
  ["INTERSTELLAR", "Nolan-Film über Raumfahrt und Zeit"],
  ["OPPENHEIMER", "Nolan-Film über die Atombombe (2023)"],
  ["AVENGERS", "Superheldenteam von Marvel"],
  ["IRONMAN", "Tony Stark in Rüstung"],
  ["HULK", "Grüner Riese, wenn Bruce Banner wütend wird"],
  ["THOR", "Donnergott mit Hammer bei Marvel"],
  ["LOKI", "Thors hinterlistiger Bruder"],
  ["THANOS", "Schnippte die halbe Menschheit weg"],
  ["GROOT", "Baumwesen, das nur seinen Namen sagt"],
  ["DEADPOOL", "Vorlauter Antiheld in rotem Anzug"],
  ["SUPERMAN", "Held aus Krypton"],
  ["ROBIN", "Batmans Sidekick"],
  ["WOLVERINE", "X-Men-Held mit Krallen"],
  ["DARTHVADER", "„Ich bin dein Vater“"],
  ["LUKE", "Skywalker, dessen Vater ein Sith ist"],
  ["LEIA", "Prinzessin mit Haarschnecken"],
  ["CHEWBACCA", "Haariger Wookiee"],
  ["JEDI", "Ritter mit Lichtschwert"],
  ["STARTREK", "Raumschiff Enterprise ist hier unterwegs"],
  ["SPOCK", "Vulkanier mit spitzen Ohren"],
  ["HARRYPOTTER", "Zauberlehrling mit Blitznarbe"],
  ["HERMINE", "Klügste Hexe ihres Jahrgangs"],
  ["RON", "Harrys rothaariger Freund"],
  ["DUMBLEDORE", "Schulleiter mit langem Bart"],
  ["VOLDEMORT", "Er, dessen Name nicht genannt werden darf"],
  ["HAGRID", "Halbriese und Wildhüter"],
  ["QUIDDITCH", "Sport auf Besen"],
  ["MUGGEL", "Nichtmagischer Mensch bei Harry Potter"],
  ["FRODO", "Hobbit, der den Ring trägt"],
  ["GOLLUM", "„Mein Schatz!“"],
  ["SAURON", "Dunkler Herrscher mit Flammenauge"],
  ["HOBBIT", "Kleiner Bewohner des Auenlands"],
  ["NARNIA", "Fantasiewelt hinter dem Kleiderschrank"],
  ["TWILIGHT", "Vampir-Romanze mit Bella und Edward"],
  ["HUNGERGAMES", "Dystopie mit Katniss Everdeen (engl. Titel)"],
  ["JAMESBOND", "Agent 007"],
  ["INDIANAJONES", "Archäologe mit Hut und Peitsche"],
  ["TERMINATOR", "„I'll be back“"],
  ["ROCKY", "Boxer aus Philadelphia, gespielt von Stallone"],
  ["JOKER", "Grinsender Batman-Gegner"],
  ["BARBIE", "Puppe, deren Film 2023 rosa Kinosäle füllte"],
  ["KEN", "Barbies Freund, der im Film „just“ sein will"],
  ["GODZILLA", "Japanisches Riesenmonster"],
  ["KINGKONG", "Riesenaffe auf dem Empire State Building"],
  ["ALIEN", "Außerirdisches im Weltall, das niemand schreien hört"],
  ["ZOMBIE", "Untoter, der „Gehirn!“ stöhnt"],
  ["VAMPIR", "Mag kein Knoblauch und kein Tageslicht"],
  ["DRACULA", "Berühmtester Vampir aus Transsilvanien"],
  ["WINNETOU", "Apachenhäuptling von Karl May"],
  ["PIPPI", "Rothaarige mit Pferd auf der Veranda"],
  ["PINOCCHIO", "Holzpuppe, deren Nase beim Lügen wächst"],
  ["ASTERIX", "Gallier mit Zaubertrank"],
  ["OBELIX", "Hinkelsteinträger, als Kind in den Zaubertrank gefallen"],
  ["IDEFIX", "Kleiner Hund eines Galliers"],
  ["TIM", "Belgischer Reporter mit Hund Struppi"],
  ["GARFIELD", "Kater, der Lasagne liebt und Montage hasst"],
  ["SNOOPY", "Beagle auf der Hundehütte"],
  ["NARUTO", "Ninja-Anime mit orangem Helden"],
  ["ONEPIECE", "Piraten-Manga mit Strohhut-Ruffy"],
  ["POKEMON", "Fangen sie alle!"],
  ["PIKACHU", "Gelbes Elektro-Pokémon"],
  ["SAILORMOON", "Anime-Heldin im Matrosenkostüm"],
  ["DRAGONBALL", "Anime mit Son Goku"],
  ["GHIBLI", "Japanisches Studio von „Chihiros Reise“"],
  ["TOTORO", "Großes Waldgeist-Wesen von Studio Ghibli"],
  ["SCOOBYDOO", "Dogge, die mit Freunden Geister jagt"],
  ["TOMUNDJERRY", "Katz-und-Maus-Duo im Zeichentrick"],
  ["BUGSBUNNY", "„Was gibt's Neues, Doc?“"],
  ["MRBEAN", "Rowan Atkinsons fast stumme Figur"],
  ["TATORT", "Krimi, nach dem sonntags getwittert wird"],

  // ---------- Musik ----------
  ["BEATLES", "Pilzköpfe aus Liverpool"],
  ["QUEEN", "Band von Freddie Mercury"],
  ["ABBA", "Schwedische Band mit „Dancing Queen“"],
  ["RAMMSTEIN", "Deutsche Band mit Flammenwerfern auf der Bühne"],
  ["METALLICA", "Metalband mit „Nothing Else Matters“"],
  ["COLDPLAY", "Band, deren Kiss-Cam-Moment 2025 viral ging"],
  ["NIRVANA", "Grunge-Band von Kurt Cobain"],
  ["OASIS", "Britpop-Band der Gallagher-Brüder"],
  ["ACDC", "Australische Rockband mit Angus Young in Schuluniform"],
  ["TOKIOHOTEL", "Deutsche Band von Bill und Tom Kaulitz"],
  ["SCOOTER", "Techno-Band mit H.P. Baxxter"],
  ["KRAFTWERK", "Düsseldorfer Elektropioniere"],
  ["DAFTPUNK", "Französisches Duo mit Robotermasken"],
  ["BTS", "K-Pop-Boygroup aus sieben Mitgliedern"],
  ["KPOP", "Musikrichtung aus Korea"],
  ["BEYONCE", "Queen B"],
  ["RIHANNA", "Sängerin von „Umbrella“"],
  ["SHAKIRA", "Kolumbianische Sängerin mit Hüftschwung"],
  ["MADONNA", "Queen of Pop"],
  ["DRAKE", "Kanadischer Rapper"],
  ["BILLIE", "Vorname der Sängerin Eilish"],
  ["TAYLOR", "Vorname von Swift"],
  ["ELVIS", "King of Rock 'n' Roll"],
  ["HELENE", "Atemlos durch die Nacht singt sie"],
  ["NENA", "Sang von 99 Luftballons"],
  ["APACHE", "Rapper mit „Roller“"],
  ["CRO", "Rapper mit Pandamaske"],
  ["SIDO", "Rapper, der früher eine Maske trug"],
  ["CAPITAL", "Rapper aus Berlin: … Bra"],
  ["PETERFOX", "Sänger von „Haus am See“"],
  ["TECHNO", "Musik, die im Berghain läuft"],
  ["HIPHOP", "Musikkultur mit Rap und Breakdance"],
  ["REGGAE", "Musik von Bob Marley"],
  ["PUNK", "Musik mit Irokesenschnitt"],
  ["METAL", "Laute Musik mit Pommesgabel"],
  ["SCHLAGER", "Musik für Ballermann und Fernsehgarten"],
  ["DISCO", "Musik der Siebziger mit Glitzerkugel"],
  ["HOUSE", "Elektronische Musik aus Chicago"],
  ["INDIE", "Musik abseits großer Labels"],
  ["BEAT", "Grundrhythmus eines Songs"],
  ["REMIX", "Neu abgemischte Version eines Songs"],
  ["COVER", "Neuinterpretation eines Songs"],
  ["FEATURE", "Gastauftritt auf einem Song (ft.)"],
  ["SINGLE", "Ausgekoppelter Song – oder Mensch ohne Partner"],
  ["VINYL", "Schallplatte, die ein Comeback feiert"],
  ["KOPFHOERER", "Noise-Cancelling-Gerät für die Ohren"],
  ["EUROVISION", "Gesangswettbewerb mit null Punkten für Deutschland"],
  ["GRAMMY", "Wichtigster Musikpreis der USA"],
  ["ROCKAMRING", "Festival in der Eifel"],

  // ---------- Games ----------
  ["XBOX", "Spielkonsole von Microsoft"],
  ["SWITCH", "Nintendo-Konsole zum Mitnehmen"],
  ["GAMEBOY", "Nintendos Taschenkonsole von 1989"],
  ["SEGA", "Firma hinter Sonic"],
  ["SONIC", "Blauer Igel, der schnell rennt"],
  ["LUIGI", "Marios Bruder in Grün"],
  ["YOSHI", "Grüner Dino, auf dem Mario reitet"],
  ["ZELDA", "Prinzessin, nach der Links Spiele benannt sind"],
  ["LINK", "Held in grüner Mütze aus Hyrule"],
  ["KIRBY", "Rosa Kugel, die Gegner einsaugt"],
  ["PACMAN", "Gelber Kreis, der Punkte frisst"],
  ["PONG", "Ur-Videospiel mit zwei Balken und einem Punkt"],
  ["ROBLOX", "Spieleplattform, die Kinder lieben"],
  ["AMONGUS", "Spiel, in dem man den Verräter sucht"],
  ["SIMS", "Lebenssimulation, in der man Leitern entfernt"],
  ["GTA", "Spielreihe um Autodiebstahl (Abk.)"],
  ["FIFA", "Fußballverband – und Videospielreihe"],
  ["ZOCKER", "Leidenschaftlicher Gamer"],
  ["CONTROLLER", "Gamepad in der Hand"],
  ["JOYSTICK", "Steuerknüppel am Computer"],
  ["LEVEL", "Spielstufe"],
  ["BOSS", "Endgegner im Spiel – oder Chef"],
  ["GAMEOVER", "Bildschirmtext beim letzten Leben"],
  ["CHEAT", "Mogel-Code im Videospiel"],
  ["NOOB", "Anfänger beim Zocken"],
  ["LAN", "…-Party: Zocken mit Kabeln (Abk.)"],
  ["ESPORT", "Wettkampf-Gaming"],
  ["ANGRYBIRDS", "Handyspiel mit wütenden Vögeln"],
  ["CANDYCRUSH", "Handyspiel mit bunten Süßigkeiten"],
  ["WORDLE", "Online-Worträtsel mit grünen und gelben Kästchen"],
  ["SUDOKU", "Zahlenrätsel mit neun Feldern"],
  ["MONOPOLY", "Brettspiel mit Schlossallee"],
  ["CATAN", "Brettspiel mit Schafen und Lehm"],
  ["UNO", "Kartenspiel mit Plus-vier-Karte"],
  ["SCRABBLE", "Brettspiel mit Buchstabensteinen"],
  ["JENGA", "Turm aus Holzklötzen, der einstürzt"],
  ["TWISTER", "Verrenkungsspiel auf bunter Matte"],
  ["ZAUBERWUERFEL", "Bunter Würfel zum Drehen"],
  ["TAMAGOTCHI", "Digitales Haustier am Schlüsselbund"],
  ["FURBY", "Plapperndes Plüschtier der 90er"],
  ["LABUBU", "Hässlich-süße Plüschfigur, Hype 2025"],
  ["FIDGETSPINNER", "Kreisel-Hype von 2017"],

  // ---------- Marken & Konsum ----------
  ["APPLE", "Konzern mit angebissenem Logo"],
  ["MCDONALDS", "Fast-Food-Kette mit goldenem M"],
  ["BURGERKING", "Fast-Food-Kette mit Whopper"],
  ["SUBWAY", "Sandwichkette mit „Sub des Tages“"],
  ["KFC", "Fast-Food-Kette mit frittiertem Hähnchen (Abk.)"],
  ["STARBUCKS", "Kaffeekette mit Meerjungfrau-Logo"],
  ["NUTELLA", "Nuss-Nougat-Creme im Glas"],
  ["HARIBO", "Macht Kinder froh"],
  ["MILKA", "Schokolade mit lila Kuh"],
  ["RITTERSPORT", "Quadratisch, praktisch, gut"],
  ["COLA", "Braune Brause"],
  ["FANTA", "Orangenlimo, ursprünglich aus Deutschland"],
  ["SPRITE", "Zitronenlimo mit grüner Flasche"],
  ["REDBULL", "Verleiht angeblich Flügel"],
  ["CLUBMATE", "Koffeinbrause der Hackerszene"],
  ["APEROL", "Orangefarbener Spritz-Klassiker"],
  ["HUGO", "Sommerdrink mit Holunder und Minze"],
  ["IKEA", "Möbelhaus mit Hotdogs am Ausgang"],
  ["ALDI", "Discounter, aufgeteilt in Nord und Süd"],
  ["LIDL", "Discounter aus Neckarsulm"],
  ["REWE", "Supermarkt in Rot"],
  ["EDEKA", "Supermarkt, der Lebensmittel liebt"],
  ["ROSSMANN", "Drogerie mit rotem Logo"],
  ["PRIMARK", "Billiges Modehaus aus Irland"],
  ["ZARA", "Spanische Modekette"],
  ["PUMA", "Raubkatze – und Sportmarke aus Herzogenaurach"],
  ["GUCCI", "Italienische Luxusmarke"],
  ["PRADA", "Trägt der Teufel laut Filmtitel"],
  ["ROLEX", "Luxusuhr mit Krone"],
  ["CROCS", "Gummiclogs mit Löchern"],
  ["BIRKENSTOCK", "Korksandale, einst Öko, heute hip"],
  ["CONVERSE", "Chucks-Hersteller"],
  ["VANS", "Skaterschuhe mit Schachbrettmuster"],
  ["LEVIS", "Jeansmarke aus San Francisco"],
  ["NIVEA", "Blaue Dose mit Creme"],
  ["TEMPO", "Taschentuch, das zum Gattungsnamen wurde"],
  ["TESA", "Klebefilm, den alle so nennen"],
  ["LEGO", "Klemmbausteine aus Billund"],
  ["PORSCHE", "Sportwagenbauer aus Zuffenhausen"],
  ["AUDI", "Autobauer mit vier Ringen"],
  ["BMW", "Bayerische Motoren Werke (Abk.)"],
  ["OPEL", "Autobauer aus Rüsselsheim"],
  ["FERRARI", "Rotes Pferd aus Maranello"],
  ["TOYOTA", "Japanischer Autoriese mit dem Prius"],
  ["SKODA", "Tschechische Automarke"],
  ["FIAT", "Italienischer Autobauer des Cinquecento"],
  ["VOLVO", "Schwedische Automarke, bekannt für Sicherheit"],
  ["TESLA", "E-Autos von Elon Musk"],
  ["SPACEX", "Raketenfirma von Elon Musk"],
  ["SMART", "Winziger Zweisitzer"],
  ["MINI", "Kleiner Brite – oder kurzer Rock"],
  ["KAEFER", "VW-Klassiker mit runder Form"],
  ["BULLI", "VW-Bus der Hippies"],
  ["LUFTHANSA", "Airline mit Kranich"],
  ["RYANAIR", "Billigflieger aus Irland"],
  ["EASYJET", "Orangefarbene Billig-Airline"],
  ["ADAC", "Gelbe Engel (Abk.)"],
  ["DHL", "Gelbe Pakettransporter (Abk.)"],
  ["HERMES", "Paketdienst, benannt nach einem Götterboten"],
  ["SPARKASSE", "Rotes S auf der Bankfiliale"],
  ["BAHNCARD", "Rabattkarte für Zugfahrten"],
  ["TICKET", "Fahrschein oder Konzertkarte"],
  ["BOARDINGPASS", "Bordkarte mit QR-Code"],
  ["COUCH", "Dorthin zieht man sich zum Streamen zurück"],

  // ---------- Moderne Begriffe allgemein ----------
  ["WORKLIFEBALANCE", "Gleichgewicht, das Gen Z einfordert"],
  ["BURNOUT", "Ausgebrannt sein"],
  ["ACHTSAMKEIT", "Trendwort für bewusstes Leben"],
  ["MEDITATION", "Stilles Sitzen mit App-Begleitung"],
  ["DETOX", "Entgiftungskur, auch digital"],
  ["SUPERFOOD", "Chiasamen und Goji-Beeren, angeblich"],
  ["CHIASAMEN", "Quellen im Pudding auf"],
  ["QUINOA", "Inka-Korn im Bowl"],
  ["BOWL", "Schüssel mit buntem Gesundessen"],
  ["POKE", "Hawaiianische Fisch-Bowl"],
  ["RAMEN", "Japanische Nudelsuppe"],
  ["TACO", "Mexikanischer Snack im gefalteten Fladen"],
  ["BURRITO", "Gerollter Wrap aus Mexiko"],
  ["WRAP", "Gerollter Fladen mit Füllung"],
  ["BAGEL", "Brötchen mit Loch"],
  ["DONUT", "Ring aus frittiertem Teig mit Glasur"],
  ["BROWNIE", "Saftiges Schokoquadrat"],
  ["MUFFIN", "Kleiner Kuchen in Papierförmchen"],
  ["CUPCAKE", "Muffin mit Sahnehaube"],
  ["CHEESECAKE", "Käsekuchen auf Amerikanisch"],
  ["PANCAKE", "Dicker Pfannkuchen mit Ahornsirup"],
  ["NACHOS", "Tortilla-Chips mit Käsesoße"],
  ["GUACAMOLE", "Avocado-Dip"],
  ["HUMMUS", "Kichererbsenpüree"],
  ["OATLY", "Haferdrink-Marke aus Schweden"],
  ["LATTE", "Kurz für Milchkaffee im Glas"],
  ["FLATWHITE", "Kaffee mit wenig Milchschaum"],
  ["COLDBREW", "Kalt aufgebrühter Kaffee"],
  ["MATE", "Südamerikanischer Tee – oder Kumpel auf Englisch"],
  ["KOMBUCHA", "Fermentierter Tee-Trend"],
  ["SPRITZ", "Aperitif mit Prosecco"],
  ["GINTONIC", "Wacholder plus Bitterlimo"],
  ["SHOT", "Kurzer Schnaps"],
  ["KATER", "Folge zu vieler Shots"],
  ["AFTERWORK", "Feierabendparty nach dem Büro"],
  ["CLUB", "Ort zum Feiern mit Türsteher"],
  ["TUERSTEHER", "Entscheidet, wer reinkommt"],
  ["GAESTELISTE", "Wer draufsteht, kommt umsonst rein"],
  ["RAVE", "Elektro-Party bis zum Morgen"],
  ["SPAETI", "Berliner Kiosk mit Wegbier"],
  ["WEGBIER", "Flasche für den Weg zur Party"],
  ["WGCASTING", "Vorstellungsgespräch für ein Zimmer"],
  ["MITBEWOHNER", "Teilt Küche und Bad"],
  ["PUTZPLAN", "Hängt in der WG-Küche und wird ignoriert"],
  ["HAMSTERKAUF", "Panisches Klopapier-Horten"],
  ["KLOPAPIER", "War 2020 plötzlich Mangelware"],
  ["PANDEMIE", "Weltweite Seuche"],
  ["CORONA", "Virus von 2020 – oder Bier mit Limette"],
  ["INZIDENZ", "Zahl, die 2020 jeder kannte"],
  ["QUARANTAENE", "Isolation zu Hause"],
  ["DESINFEKTION", "Gel am Supermarkteingang"],
  ["KLIMAKLEBER", "Aktivist, der sich auf der Straße festklebt"],
  ["GRETA", "Vorname der Klimaaktivistin aus Schweden"],
  ["ELEKTROROLLER", "Liegt umgekippt auf dem Gehweg"],
  ["LASTENRAD", "Fahrrad mit Kiste für Kinder"],
  ["CARSHARING", "Auto teilen statt besitzen"],
  ["WALLBOX", "Ladestation in der Garage"],
  ["WAERMEPUMPE", "Heizung, um die 2023 heftig gestritten wurde"],
  ["BALKONKRAFTWERK", "Mini-Solaranlage am Geländer"],
  ["GENZ", "Generation nach den Millennials"],
  ["MILLENNIAL", "Generation Y, mit Avocado-Toast"],
  ["BOOMER", "Ok, … – Spott über Ältere"],
  ["SLAY", "Jugendwort: etwas mit Bravour meistern"],
  ["LOST", "Jugendwort für ahnungslos"],
  ["SUS", "Jugendwort für verdächtig"],
  ["WILD", "Jugendwort für krass"],
  ["SMASH", "Jugendwort: jemanden attraktiv finden"],
  ["RIZZ", "Englischer Slang für Flirt-Charme"],
  ["AURA", "Jugendwort 2024 für Ausstrahlung"],
  ["SIGMA", "Jugendsprachlich: einsamer Wolf, Alpha-Ersatz"],
  ["DIGGI", "Verniedlichung von Digga"],
  ["BRO", "Kumpel, englisch kurz"],
  ["BAE", "Kosewort für den Schatz"],
  ["LOL", "Laut lachen im Chat (Abk.)"],
  ["OMG", "Oh mein Gott, im Chat (Abk.)"],
  ["YOLO", "Man lebt nur einmal (Abk.)"],
  ["FOMO", "Angst, etwas zu verpassen (Abk.)"],
  ["HYPE", "Großer Rummel um etwas"],
  ["TREND", "Ist gerade angesagt"],
  ["LIFEHACK", "Cleverer Alltagstrick"],
  ["VIBE", "Stimmung, Atmosphäre"],
  ["CHILL", "Entspannt"],
  ["COOL", "Lässig"],
  ["NICE", "Englisch für nett, auch im Deutschen benutzt"],
  ["FAKE", "Gefälscht"],
  ["FAKENEWS", "Falschmeldungen im Netz"],
  ["DEEPFAKE", "KI-gefälschtes Video"],
  ["BOT", "Automatisierter Account"],
  ["PROMPT", "Anweisung an eine KI"],
);
